### ISSUE TITLE
Via Addon Manager installed Freecad Gears failed to "load".

### ISSUE THREAD

**Issue by ElPatoNoEsTu** [realthunder/FreeCAD#1015]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 2024.408.0.14555 (Git shallow)
Build type: Release
Branch: (HEAD detached at 20240407stable)
Hash: 973e4821bcd19a5a1af9ae3e1d2ed961aad0a8ab
Python 3.11.8, Qt 5.15.6, Coin 4.0.1, Vtk 9.2.5, OCC 7.7.1
Locale: German/Germany (de_DE)
Installed mods: 
  * A2plus.backup1698606179.0777142
  * Assembly3.backup1701122976.354356 0.11.3
  * Curves.backup1701123223.0435972
  * freecad.gears 1.2.0
  * LCInterlocking
[/code]
```

### Subproject(s) affected?

None

### Problem description

Via Addon Manager installed Freecad Gears failed to "load".

10:00:05  During initialization the error "cannot import name 'app' from 'freecad' (C:\Users\xxxxxxxx\AppData\Roaming\FreeCAD\Mod\Assembly3.backup1701122976.354356\.\freecad\__init__.py)" occurred in freecad.gears
10:00:05  --------------------------------------------------------------------------------
10:00:05  Traceback (most recent call last):
  File "<string>", line 231, in InitApplications
  File "C:\Temp\FreeCAD-Link-Stable-Win-x86_64-py3.11-20240407\bin\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\xxxxxxxx\AppData\Roaming\FreeCAD\Mod\freecad.gears\.\freecad\gears\init_gui.py", line 21, in <module>
    from freecad import app
ImportError: cannot import name 'app' from 'freecad' (C:\Users\xxxxxxxx\AppData\Roaming\FreeCAD\Mod\Assembly3.backup1701122976.354356\.\freecad\__init__.py)
10:00:05  --------------------------------------------------------------------------------

### Anything else?

All suggestions are welcome.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ElPatoNoEsTu** [comment]
I finaly figured out that this was caused by a "Backup-Folder" in my C:\Users\xxxxxxxx\AppData\Roaming\FreeCAD\Mod\  Folder.
It seems that somewhen ( might be years ago ) these backups of some addons were made, but I never noticed them before.

**Comment by ElPatoNoEsTu** [comment]
I finaly figured out that this was caused by a "Backup-Folder" in my C:\Users\xxxxxxxx\AppData\Roaming\FreeCAD\Mod\  Folder.
It seems that somewhen ( might be years ago ) these backups of some addons were made, but I never noticed them before.
