### ISSUE TITLE
Path Workbench - operation Adaptive fails to load task menu.  Works in version .19 24291

### ISSUE THREAD

**Issue by j-keiter** [realthunder/FreeCAD#198]
Report View
```
15:02:38  Traceback (most recent call last):
  File "/tmp/.mount_FreeCAUZqULn/usr/Mod/Path/PathScripts/PathOpGui.py", line 104, in setEdit
    self.setupTaskPanel(TaskPanel(vobj.Object, self.deleteObjectsOnReject(), page, selection))
  File "/tmp/.mount_FreeCAUZqULn/usr/Mod/Path/PathScripts/PathOpGui.py", line 1028, in __init__
    self.featurePages.append(opPage.taskPanelBaseLocationPage(obj, features))
  File "/tmp/.mount_FreeCAUZqULn/usr/Mod/Path/PathScripts/PathAdaptiveGui.py", line 247, in taskPanelBaseLocationPage
    self.extensionsPanel = PathFeatureExtensionsGui.TaskPanelExtensionPage(obj, features) # pylint: disable=attribute-defined-outside-init
  File "/tmp/.mount_FreeCAUZqULn/usr/Mod/Path/PathScripts/PathOpGui.py", line 201, in __init__
    self.form = self.getForm()  # pylint: disable=assignment-from-no-return
  File "/tmp/.mount_FreeCAUZqULn/usr/Mod/Path/PathScripts/PathFeatureExtensionsGui.py", line 230, in getForm
    form.enableExtensionsWarning.hide()
<class 'AttributeError'>: 'PySide2.QtWidgets.QWidget' object has no attribute 'enableExtensionsWarning'
15:03:01  Traceback (most recent call last):
  File "/tmp/.mount_FreeCAUZqULn/usr/Mod/Path/PathScripts/PathOpGui.py", line 104, in setEdit
    self.setupTaskPanel(TaskPanel(vobj.Object, self.deleteObjectsOnReject(), page, selection))
  File "/tmp/.mount_FreeCAUZqULn/usr/Mod/Path/PathScripts/PathOpGui.py", line 1028, in __init__
    self.featurePages.append(opPage.taskPanelBaseLocationPage(obj, features))
  File "/tmp/.mount_FreeCAUZqULn/usr/Mod/Path/PathScripts/PathAdaptiveGui.py", line 247, in taskPanelBaseLocationPage
    self.extensionsPanel = PathFeatureExtensionsGui.TaskPanelExtensionPage(obj, features) # pylint: disable=attribute-defined-outside-init
  File "/tmp/.mount_FreeCAUZqULn/usr/Mod/Path/PathScripts/PathOpGui.py", line 201, in __init__
    self.form = self.getForm()  # pylint: disable=assignment-from-no-return
  File "/tmp/.mount_FreeCAUZqULn/usr/Mod/Path/PathScripts/PathFeatureExtensionsGui.py", line 230, in getForm
    form.enableExtensionsWarning.hide()
<class 'AttributeError'>: 'PySide2.QtWidgets.QWidget' object has no attribute 'enableExtensionsWarning'
```

OS: Debian GNU/Linux 11 (bullseye) (GNOME/gnome-xorg)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.1015.24301 +3962 (Git) AppImage
Build type: Release
Branch: LinkStage3
Hash: c6cb39697eb439caf7e5bd0208ca3082a7820547
Python version: 3.9.7
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.2
Locale: English/United States (en_US)

**Comment by luzpaz** [comment]
@j-keiter please test on LinkDaily next time as well as upstream v0.20dev?

**Comment by ngocminhdao88** [comment]
Not sure if it the same error, but i also got an error regarding 3d pocket on daily Windows version. Linux version works fine. I got this problem solved by copying three files PathUtils.py, PathOp.py and PathAreaOp.py (found in Mod\Path\PathScripts) from official version over.

**Comment by luzpaz** [comment]
@realthunder is pretty busy with FreeCAD master release stuff. It sounds like @ngocminhdao88 has found a workaround. I wonder if there is a quick way to diff those 3 files between Link branch and upstream master to see if the overwrite creates other regressions while it fixes the issue in this ticket?
