### ISSUE TITLE
Running all Test WB on LinkDaily is problematic

### ISSUE THREAD

**Issue by luzpaz** [realthunder/FreeCAD#301]
@realthunder is there a way to tell TestWB (when running in the GUI) to automatically say yes to any recompute requests for opening unit test files?
I recommend not running tests in the GUI until you figure that out (because you're potentially pressing the enter key hundreds of times!). I'm running LinkDaily from console now to see how it fairs. 

Here are the results of running `freecad-realthunder.cmd -t 0`
```shell
======================================================================
ERROR: testCTRIA3Element (MeshTestsApp.NastranReader)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/snap/freecad-realthunder/14/usr/Mod/Mesh/MeshTestsApp.py", line 583, in testCTRIA3Element
    m = Mesh.read(f"{self.test_dir}/NASTRAN_Test_GRID_CTRIA3.bdf")
RuntimeError: File does not exist: /snap/freecad-realthunder/14/usr/Mod/Mesh/App/TestData/NASTRAN_Test_GRID_CTRIA3.bdf

======================================================================
ERROR: testDelimitedGRIDElement (MeshTestsApp.NastranReader)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/snap/freecad-realthunder/14/usr/Mod/Mesh/MeshTestsApp.py", line 573, in testDelimitedGRIDElement
    m = Mesh.read(f"{self.test_dir}/NASTRAN_Test_Delimited_GRID_CQUAD4.bdf")
RuntimeError: File does not exist: /snap/freecad-realthunder/14/usr/Mod/Mesh/App/TestData/NASTRAN_Test_Delimited_GRID_CQUAD4.bdf

======================================================================
ERROR: testEightCharGRIDElement (MeshTestsApp.NastranReader)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/snap/freecad-realthunder/14/usr/Mod/Mesh/MeshTestsApp.py", line 568, in testEightCharGRIDElement
    m = Mesh.read(f"{self.test_dir}/NASTRAN_Test_GRID_CQUAD4.bdf")
RuntimeError: File does not exist: /snap/freecad-realthunder/14/usr/Mod/Mesh/App/TestData/NASTRAN_Test_GRID_CQUAD4.bdf

======================================================================
ERROR: testSixteenCharGRIDElement (MeshTestsApp.NastranReader)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/snap/freecad-realthunder/14/usr/Mod/Mesh/MeshTestsApp.py", line 578, in testSixteenCharGRIDElement
    m = Mesh.read(f"{self.test_dir}/NASTRAN_Test_GRIDSTAR_CQUAD4.bdf")
RuntimeError: File does not exist: /snap/freecad-realthunder/14/usr/Mod/Mesh/App/TestData/NASTRAN_Test_GRIDSTAR_CQUAD4.bdf

======================================================================
ERROR: test00 (PathTests.TestPathStock.TestPathStock)
Test CreateBox
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/snap/freecad-realthunder/14/usr/Mod/Path/PathTests/TestPathStock.py", line 48, in setUp
    self.job.addProperty('App::PropertyLink', 'Proxy')
RuntimeError: Property TestPathStock#Job.Proxy already exists

======================================================================
ERROR: test01 (PathTests.TestPathStock.TestPathStock)
Test CreateCylinder
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/snap/freecad-realthunder/14/usr/Mod/Path/PathTests/TestPathStock.py", line 48, in setUp
    self.job.addProperty('App::PropertyLink', 'Proxy')
RuntimeError: Property TestPathStock1#Job.Proxy already exists

======================================================================
ERROR: test10 (PathTests.TestPathStock.TestPathStock)
Verify FromTemplate box creation.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/snap/freecad-realthunder/14/usr/Mod/Path/PathTests/TestPathStock.py", line 48, in setUp
    self.job.addProperty('App::PropertyLink', 'Proxy')
RuntimeError: Property TestPathStock2#Job.Proxy already exists

======================================================================
ERROR: test11 (PathTests.TestPathStock.TestPathStock)
Verify FromTemplate cylinder creation.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/snap/freecad-realthunder/14/usr/Mod/Path/PathTests/TestPathStock.py", line 48, in setUp
    self.job.addProperty('App::PropertyLink', 'Proxy')
RuntimeError: Property TestPathStock3#Job.Proxy already exists

======================================================================
ERROR: test12 (PathTests.TestPathStock.TestPathStock)
Verify FromTemplate from Base creation.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/snap/freecad-realthunder/14/usr/Mod/Path/PathTests/TestPathStock.py", line 48, in setUp
    self.job.addProperty('App::PropertyLink', 'Proxy')
RuntimeError: Property TestPathStock4#Job.Proxy already exists

======================================================================
ERROR: testSchemeTranslation (UnitTests.UnitBasicCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/snap/freecad-realthunder/14/usr/Mod/Test/UnitTests.py", line 126, in testSchemeTranslation
    q2 = FreeCAD.Units.Quantity(t[0])
ValueError: syntax error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/freecad-realthunder/14/usr/Mod/Test/UnitTests.py", line 131, in testSchemeTranslation
    print (" ".join(e).encode("utf-8").strip())
TypeError: can only join an iterable

======================================================================
FAIL: test_ccx_buckling_flexuralbuckling (femtest.app.test_solver_calculix.TestSolverCalculix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/snap/freecad-realthunder/14/usr/Mod/Fem/femtest/app/test_solver_calculix.py", line 104, in test_ccx_buckling_flexuralbuckling
    self.input_file_writing_test(get_namefromdef("test_"))
  File "/snap/freecad-realthunder/14/usr/Mod/Fem/femtest/app/test_solver_calculix.py", line 397, in input_file_writing_test
    self.assertFalse(
AssertionError: 'Comparing /snap/freecad-realthunder/14/usr/Mod/Fem/femtest/data/calculix/ccx_buckling_flexuralbuckling.inp to /tmp/FEM_unittests/solver_calculix_ccx_buckling_flexuralbuckling_d6716f87f054/Mesh.inp failed!\n--- \n+++ \n@@ -767,25 +767,25 @@\n-65,3,-3.2812500000000E-01\n-66,3,-6.5625000000000E-01\n-67,3,-6.5625000000000E-01\n-68,3,-1.3125000000000E+00\n-101,3,-6.5625000000000E-01\n-102,3,-1.3125000000000E+00\n-135,3,-6.5625000000000E-01\n-136,3,-1.3125000000000E+00\n-169,3,-3.2812500000000E-01\n-170,3,-6.5625000000000E-01\n-203,3,-6.5625000000000E-01\n-204,3,-1.3125000000000E+00\n-221,3,-1.3125000000000E+00\n-238,3,-1.3125000000000E+00\n-255,3,-6.5625000000000E-01\n-288,3,-6.5625000000000E-01\n-289,3,-1.3125000000000E+00\n-306,3,-1.3125000000000E+00\n-323,3,-1.3125000000000E+00\n-340,3,-6.5625000000000E-01\n-373,3,-3.2812500000000E-01\n-374,3,-6.5625000000000E-01\n-391,3,-6.5625000000000E-01\n-408,3,-6.5625000000000E-01\n-425,3,-3.2812500000000E-01\n+65,3,3.2812500000000E-01\n+66,3,6.5625000000000E-01\n+67,3,6.5625000000000E-01\n+68,3,1.3125000000000E+00\n+101,3,6.5625000000000E-01\n+102,3,1.3125000000000E+00\n+135,3,6.5625000000000E-01\n+136,3,1.3125000000000E+00\n+169,3,3.2812500000000E-01\n+170,3,6.5625000000000E-01\n+203,3,6.5625000000000E-01\n+204,3,1.3125000000000E+00\n+221,3,1.3125000000000E+00\n+238,3,1.3125000000000E+00\n+255,3,6.5625000000000E-01\n+288,3,6.5625000000000E-01\n+289,3,1.3125000000000E+00\n+306,3,1.3125000000000E+00\n+323,3,1.3125000000000E+00\n+340,3,6.5625000000000E-01\n+373,3,3.2812500000000E-01\n+374,3,6.5625000000000E-01\n+391,3,6.5625000000000E-01\n+408,3,6.5625000000000E-01\n+425,3,3.2812500000000E-01\n' is not false : CalculiX write_inp_file for ccx_buckling_flexuralbuckling test failed.
Comparing /snap/freecad-realthunder/14/usr/Mod/Fem/femtest/data/calculix/ccx_buckling_flexuralbuckling.inp to /tmp/FEM_unittests/solver_calculix_ccx_buckling_flexuralbuckling_d6716f87f054/Mesh.inp failed!
--- 
+++ 
@@ -767,25 +767,25 @@
-65,3,-3.2812500000000E-01
-66,3,-6.5625000000000E-01
-67,3,-6.5625000000000E-01
-68,3,-1.3125000000000E+00
-101,3,-6.5625000000000E-01
-102,3,-1.3125000000000E+00
-135,3,-6.5625000000000E-01
-136,3,-1.3125000000000E+00
-169,3,-3.2812500000000E-01
-170,3,-6.5625000000000E-01
-203,3,-6.5625000000000E-01
-204,3,-1.3125000000000E+00
-221,3,-1.3125000000000E+00
-238,3,-1.3125000000000E+00
-255,3,-6.5625000000000E-01
-288,3,-6.5625000000000E-01
-289,3,-1.3125000000000E+00
-306,3,-1.3125000000000E+00
-323,3,-1.3125000000000E+00
-340,3,-6.5625000000000E-01
-373,3,-3.2812500000000E-01
-374,3,-6.5625000000000E-01
-391,3,-6.5625000000000E-01
-408,3,-6.5625000000000E-01
-425,3,-3.2812500000000E-01
+65,3,3.2812500000000E-01
+66,3,6.5625000000000E-01
+67,3,6.5625000000000E-01
+68,3,1.3125000000000E+00
+101,3,6.5625000000000E-01
+102,3,1.3125000000000E+00
+135,3,6.5625000000000E-01
+136,3,1.3125000000000E+00
+169,3,3.2812500000000E-01
+170,3,6.5625000000000E-01
+203,3,6.5625000000000E-01
+204,3,1.3125000000000E+00
+221,3,1.3125000000000E+00
+238,3,1.3125000000000E+00
+255,3,6.5625000000000E-01
+288,3,6.5625000000000E-01
+289,3,1.3125000000000E+00
+306,3,1.3125000000000E+00
+323,3,1.3125000000000E+00
+340,3,6.5625000000000E-01
+373,3,3.2812500000000E-01
+374,3,6.5625000000000E-01
+391,3,6.5625000000000E-01
+408,3,6.5625000000000E-01
+425,3,3.2812500000000E-01


======================================================================
FAIL: testPrimitiveEllipsoid (PartDesignTests.TestPrimitive.TestPrimitive)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/snap/freecad-realthunder/14/usr/Mod/PartDesign/PartDesignTests/TestPrimitive.py", line 102, in testPrimitiveEllipsoid
    self.assertAlmostEqual(self.Ellipsoid001.Shape.Volume, 4/3.0 * pi * (2*4**2 - 1.5*3**2), places=1)
AssertionError: 77.64310811390332 != 77.49261878854823 within 1 places (0.15048932535509607 difference)

======================================================================
FAIL: testDocument (Document.DocumentObserverCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/snap/freecad-realthunder/14/usr/Mod/Test/Document.py", line 1813, in testDocument
    self.assertEqual(self.Obs.signal.pop(), 'DocAbortTransaction')
AssertionError: 'ObjChanged' != 'DocAbortTransaction'
- ObjChanged
+ DocAbortTransaction


----------------------------------------------------------------------
Ran 588 tests in 73.295s

FAILED (failures=3, errors=10)
```

```
OS: Ubuntu Core 20 (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 2022.402.14555 (Git shallow)
Build type: Release
Branch: (HEAD detached at 2022.04.02-edge)
Hash: b126e1545ee0a35aa3c9831058a384e1cc1f88fc
Python version: 3.8.10
Qt version: 5.15.3
Coin version: 4.0.1
OCC version: 7.6.1
Locale: English/United States (en_US)
````

**Comment by realthunder** [comment]
You can turn off the prompt with the following option

![image](https://user-images.githubusercontent.com/1207888/161409237-693f1dd4-4fc9-495a-bad6-360d6f9f15cb.png)

**Comment by luzpaz** [comment]
Thanks! Maybe this should be automatically by default be temporarily enabled when only running TestWB? Maybe that's overkill. Just thinking out loud.

**Comment by realthunder** [comment]
Yes, there should be something like that. I'll add it later.

**Comment by luzpaz** [comment]
Thanks for your time.
