### ISSUE TITLE
Failure to put material 

### ISSUE THREAD

**Issue by hamza00789** [realthunder/FreeCAD#367]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 2022.407.26244 +4693 (Git)
Build type: Release
Branch: LinkDaily
Hash: 9610830a8fd492b3b3d96f8328507c80f1437cda
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.6.0
Locale: English/United States (en_US)
 

When I tried to put material on it, it failed. In case of failure, the error message is something like this. 

07:41:13  Start Editing Material
07:41:13  Traceback (most recent call last):
07:41:13    File "C:\Users\hamza\AppData\Roaming\FreeCAD\Mod\Part-o-magic\PartOMagic\Gui\Observer.py", line 245, in poll
07:41:13      self.trackEditing()
07:41:13    File "C:\Users\hamza\AppData\Roaming\FreeCAD\Mod\Part-o-magic\PartOMagic\Gui\Observer.py", line 314, in trackEditing
07:41:13      self.slotStartEditing(cur_in_edit)
07:41:13    File "C:\Users\hamza\AppData\Roaming\FreeCAD\Mod\Part-o-magic\PartOMagic\Gui\Observer.py", line 208, in slotStartEditing
07:41:13      cnt = GT.getContainer(feature)
07:41:13    File "C:\Users\hamza\AppData\Roaming\FreeCAD\Mod\Part-o-magic\PartOMagic\Base\Containers.py", line 235, in getContainer
07:41:13      for dep in feat.InList:
07:41:13  AttributeError: 'dict' object has no attribute 'InList'
07:41:21  Removing Textures
07:41:21  Texturing objects
07:41:21  Removing Textures
07:41:27  Removing Textures
07:41:29  Removing Textures
07:41:29  Texturing objects
07:41:29  Texturing Cube
07:41:29  Traceback (most recent call last):
  File "C:\Users\hamza\AppData\Roaming\FreeCAD\Mod\ArchTextures\texture_config.py", line 272, in onChanged
    self.textureConfig.execute(self.Object)
  File "C:\Users\hamza\AppData\Roaming\FreeCAD\Mod\ArchTextures\texture_config.py", line 225, in execute
    self.textureManager.textureObjects()
  File "C:\Users\hamza\AppData\Roaming\FreeCAD\Mod\ArchTextures\texture_manager.py", line 105, in textureObjects
    shadedNode = faceset_utils.findShadedNode(switch)
  File "C:\Users\hamza\AppData\Roaming\FreeCAD\Mod\ArchTextures\arch_texture_utils\faceset_utils.py", line 417, in findShadedNode
    children = node.getChildren()
<class 'AttributeError'>: 'NoneType' object has no attribute 'getChildren'  

https://user-images.githubusercontent.com/92737149/163909869-1050331c-ac75-4588-b6b9-aeed826a574f.mp4

**Comment by hamza00789** [comment]
Is this the right place to describe such issues?

**Comment by hamza00789** [comment]
https://forum.freecadweb.org/viewtopic.php?f=44&t=68114
