### ISSUE TITLE
Path Workbench : Pocket Shape don’t work

### ISSUE THREAD

**Issue by Zcool85** [realthunder/FreeCAD#414]
When I click on "Pocket shape" button in Path Workbench, an error occurred.

Process to reproduce :

- Create any body part (say 100x50x10mm)
- On top face of this body part, create a pocket (say 80x30x5mm)
- Change to Path Workbench
- Create a new Job and select the body part (leave defaults)
- Select the face into the pocket
- Clic on button « Pocket Shape »

Content of Report View :

```
18:27:46  A3 available
18:34:15  <PropShape> PropertyTopoShape.cpp(402): Pending recompute for generating element map: endmill#Body
18:34:15  <PropShape> PropertyTopoShape.cpp(402): Pending recompute for generating element map: endmill#Sketch
18:34:15  <PropShape> PropertyTopoShape.cpp(402): Pending recompute for generating element map: endmill#Revolution
18:34:15  <PropShape> PropertyTopoShape.cpp(402): Pending recompute for generating element map: endmill#Revolution
18:34:19  centroid_post gcode postprocessor loaded.
18:34:19  centroid_post gcode postprocessor loaded.
18:35:16  Traceback (most recent call last):
  File "/Applications/FreeCAD.app/Contents/Resources/Mod/Path/PathScripts/PathOpGui.py", line 104, in setEdit
    self.setupTaskPanel(TaskPanel(vobj.Object, self.deleteObjectsOnReject(), page, selection))
  File "/Applications/FreeCAD.app/Contents/Resources/Mod/Path/PathScripts/PathOpGui.py", line 1028, in __init__
    self.featurePages.append(opPage.taskPanelBaseLocationPage(obj, features))
  File "/Applications/FreeCAD.app/Contents/Resources/Mod/Path/PathScripts/PathPocketShapeGui.py", line 62, in taskPanelBaseLocationPage
    self.extensionsPanel = PathFeatureExtensionsGui.TaskPanelExtensionPage(obj, features) # pylint: disable=attribute-defined-outside-init
  File "/Applications/FreeCAD.app/Contents/Resources/Mod/Path/PathScripts/PathOpGui.py", line 201, in __init__
    self.form = self.getForm()  # pylint: disable=assignment-from-no-return
  File "/Applications/FreeCAD.app/Contents/Resources/Mod/Path/PathScripts/PathFeatureExtensionsGui.py", line 230, in getForm
    form.enableExtensionsWarning.hide()
<class 'AttributeError'>: 'PySide2.QtWidgets.QWidget' object has no attribute 'enableExtensionsWarning'
```

My FreeCad version :
```
OS: macOS 10.16
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2022.430.28641 (Git)
Build type: Release
Branch: LinkStage3
Hash: a77045488092c24ece25d63c91f362cbd2181d36
Python version: 3.9.12
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.3
Locale: C/Default (C)
```

Screen capture :
<img width="1159" alt="Capture d’écran 2022-05-17 à 18 36 10" src="https://user-images.githubusercontent.com/12772987/168865824-94d06b83-ff27-411a-a42d-8a3452c320b2.png">

And the file to reproduce :
[BUG Path Workbench - Pocket Shape.FCStd.zip](https://github.com/realthunder/FreeCAD/files/8710132/BUG.Path.Workbench.-.Pocket.Shape.FCStd.zip)

Thank for your help !

**Comment by Zcool85** [comment]
My bad ! This bug is fixed in Daily version of FreeCad.

This version work well :

```
OS: macOS 10.16
Word size of FreeCAD: 64-bit
Version: 2022.430.26244 +4758 (Git)
Build type: Release
Branch: LinkDaily
Hash: b024b876480a533018fdc702145e9e38f8c54ba6
Python version: 3.9.12
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.3
Locale: C/Default (C)
```
