### ISSUE TITLE
Snap fails to install solver bindings py-slvs

### ISSUE THREAD

**Issue by wrycta** [realthunder/FreeCAD#441]
Using snap install version 2022-06-05-gf64dc664, with classic confinement (also tried a regular install first).

Startup gives the message
`<asm3.main> init_gui.py(14): no solver backend found`
in the report view.

Going to the assembly3 workbench gives the message
`Would you like to download and install the Python bindings of SolveSpace ([py-slvs](https://pypi.org/project/py-slvs/))?`

Clicking yes gives an error with the python module install
```
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/snap/freecad-realthunder/38/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 70, in main
    return command.main(cmd_args)
  File "/snap/freecad-realthunder/38/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 101, in main
    return self._main(args)
  File "/snap/freecad-realthunder/38/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 223, in _main
    self.handle_pip_version_check(options)
  File "/snap/freecad-realthunder/38/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 144, in handle_pip_version_check
    session = self._build_session(
  File "/snap/freecad-realthunder/38/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 89, in _build_session
    session = PipSession(
  File "/snap/freecad-realthunder/38/lib/python3.8/site-packages/pip/_internal/network/session.py", line 282, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/snap/freecad-realthunder/38/lib/python3.8/site-packages/pip/_internal/network/session.py", line 122, in user_agent
    linux_distribution = distro.name(), distro.version(), distro.codename()
  File "/snap/freecad-realthunder/38/lib/python3.8/site-packages/pip/_vendor/distro/distro.py", line 297, in name
    return _distro.name(pretty)
  File "/snap/freecad-realthunder/38/lib/python3.8/site-packages/pip/_vendor/distro/distro.py", line 842, in name
    self.os_release_attr("name")
  File "/snap/freecad-realthunder/38/lib/python3.8/site-packages/pip/_vendor/distro/distro.py", line 1032, in os_release_attr
    return self._os_release_info.get(attribute, "")
  File "/snap/freecad-realthunder/38/usr/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/snap/freecad-realthunder/38/lib/python3.8/site-packages/pip/_vendor/distro/distro.py", line 1070, in _os_release_info
    with open(self.os_release_file, encoding="utf-8") as release_file:
PermissionError: [Errno 13] Permission denied: '/etc/os-release'
```

Is there a way to install the solver in the snap version?

**Comment by wrycta** [comment]
This appears to be an issue with my snap setup - I think the program in the FreeCAD snap couldn't read the files from the base image.

Reinstalling the snap on a fresh install works perfectly. Closing this as user error.
