### ISSUE TITLE
Image WB, crash

### ISSUE THREAD

**Issue by snelweg** [realthunder/FreeCAD#459]
When I try to use an image in the Image WB FreeCAD Linkstage crashes everytime. It works fine in 'official' 0.20

```
~/Downloads/FreeCAD-asm3-Daily-Conda-Py3-Qt5-20220430-glibc2.12-x86_64.AppImage 
/tmp/.mount_FreeCAzCh8uD
FreeCAD 0.20, Libs: 2022.430R26244 +4758 (Git)
Sheet Metal workbench loaded
Assembly4 workbench (v0.11.12) loaded
Initializing Assembly4 workbench (v0.11.12) ............................ done.
<PropShape> PropertyTopoShape.cpp(414): Pending recompute for generating element map: EinhellRails#Body
<PropShape> PropertyTopoShape.cpp(414): Pending recompute for generating element map: EinhellRails#Sketch
Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libc.so.6(+0x38920) [0x7f1dbaf6e920]
realthunder/FreeCAD_assembly3#1  /usr/lib/x86_64-linux-gnu/dri/i965_dri.so(+0x27bf8f) [0x7f1db04c3f8f]
realthunder/FreeCAD_assembly3#2  /usr/lib/x86_64-linux-gnu/dri/i965_dri.so(+0x2c290b) [0x7f1db050a90b]
realthunder/FreeCAD_assembly3#3  /usr/lib/x86_64-linux-gnu/dri/i965_dri.so(+0x2b762e) [0x7f1db04ff62e]
realthunder/FreeCAD_assembly3#4  /usr/lib/x86_64-linux-gnu/dri/i965_dri.so(+0x5166fe) [0x7f1db075e6fe]
realthunder/FreeCAD_assembly3#5  0x7f1dbd75139d in NaviCubeShared::drawNaviCube(SoCamera*, bool, int, bool) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libFreeCADGui.so+0x13cd
realthunder/FreeCAD_assembly3#6  0x7f1dbd7517b6 in NaviCubeImplementation::drawNaviCube(bool) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libFreeCADGui.so+0x46
realthunder/FreeCAD_assembly3#7  0x7f1dbd71ba45 in Gui::View3DInventorViewer::renderScene() from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libFreeCADGui.so+0x515
realthunder/FreeCAD_assembly3#8  0x7f1dbd6cac0d in SIM::Coin3D::Quarter::QuarterWidget::paintEvent(QPaintEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libFreeCADGui.so+0x31d
realthunder/FreeCAD_assembly3#9  0x7f1dbd6d0ec5 in SIM::Coin3D::Quarter::SoQTQuarterAdaptor::paintEvent(QPaintEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libFreeCADGui.so+0x45
realthunder/FreeCAD_assembly3#10  0x7f1dbbf4595d in QWidget::event(QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x5a3
realthunder/FreeCAD_assembly3#11  0x7f1dbbfaedb7 in QFrame::event(QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x27
realthunder/FreeCAD_assembly3#12  0x7f1dbc129ebe in QGraphicsView::viewportEvent(QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x456
realthunder/FreeCAD_assembly3#13  0x7f1dbb4b0019 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Core.so.5+0xcd
realthunder/FreeCAD_assembly3#14  0x7f1dbbf1a7e1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0xcb
realthunder/FreeCAD_assembly3#15  0x7f1dbbf2031d in QApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x1ac9
realthunder/FreeCAD_assembly3#16  0x7f1dbd27d5f9 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libFreeCADGui.so+0x89
realthunder/FreeCAD_assembly3#17  0x7f1dbb4b2606 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Core.so.5+0x86
realthunder/FreeCAD_assembly3#18  0x7f1dbbf40612 in QWidgetPrivate::sendPaintEvent(QRegion const&) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x28
realthunder/FreeCAD_assembly3#19  0x7f1dbbf40d3f in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x707
realthunder/FreeCAD_assembly3#20  0x7f1dbbf414b1 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x2c1
realthunder/FreeCAD_assembly3#21  0x7f1dbbf411be in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0xb86
realthunder/FreeCAD_assembly3#22  0x7f1dbbf414b1 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x2c1
realthunder/FreeCAD_assembly3#23  0x7f1dbbf411be in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0xb86
realthunder/FreeCAD_assembly3#24  0x7f1dbbf414b1 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x2c1
realthunder/FreeCAD_assembly3#25  0x7f1dbbf411be in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0xb86
realthunder/FreeCAD_assembly3#26  0x7f1dbbf414b1 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x2c1
realthunder/FreeCAD_assembly3#27  0x7f1dbbf411be in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0xb86
realthunder/FreeCAD_assembly3#28  0x7f1dbbf414b1 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x2c1
realthunder/FreeCAD_assembly3#29  0x7f1dbbf411be in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0xb86
realthunder/FreeCAD_assembly3#30  0x7f1dbbf414b1 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x2c1
realthunder/FreeCAD_assembly3#31  0x7f1dbbf413ce in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x1de
realthunder/FreeCAD_assembly3#32  0x7f1dbbf411be in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0xb86
realthunder/FreeCAD_assembly3#33  0x7f1dbbf414b1 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x2c1
realthunder/FreeCAD_assembly3#34  0x7f1dbbf413ce in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x1de
realthunder/FreeCAD_assembly3#35  0x7f1dbbf413ce in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x1de
realthunder/FreeCAD_assembly3#36  0x7f1dbbf413ce in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x1de
realthunder/FreeCAD_assembly3#37  0x7f1dbbf413ce in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x1de
realthunder/FreeCAD_assembly3#38  0x7f1dbbf413ce in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x1de
realthunder/FreeCAD_assembly3#39  0x7f1dbbf413ce in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x1de
realthunder/FreeCAD_assembly3#40  0x7f1dbbf413ce in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x1de
realthunder/FreeCAD_assembly3#41  0x7f1dbbf413ce in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x1de
realthunder/FreeCAD_assembly3#42  0x7f1dbbf413ce in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x1de
realthunder/FreeCAD_assembly3#43  0x7f1dbbf413ce in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x1de
realthunder/FreeCAD_assembly3#44  0x7f1dbbf413ce in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x1de
realthunder/FreeCAD_assembly3#45  0x7f1dbbf411be in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0xb86
realthunder/FreeCAD_assembly3#46  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5(+0x17ed08) [0x7f1dbbf24d08]
realthunder/FreeCAD_assembly3#47  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5(+0x17efaf) [0x7f1dbbf24faf]
realthunder/FreeCAD_assembly3#48  0x7f1dbbf35dd4 in QWidgetPrivate::syncBackingStore() from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x66
realthunder/FreeCAD_assembly3#49  0x7f1dbbf45cd9 in QWidget::event(QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x91f
realthunder/FreeCAD_assembly3#50  0x7f1dbbff034f in QMainWindow::event(QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0xdd
realthunder/FreeCAD_assembly3#51  0x7f1dbbf1a7f2 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0xdc
realthunder/FreeCAD_assembly3#52  0x7f1dbbf2031d in QApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x1ac9
realthunder/FreeCAD_assembly3#53  0x7f1dbd27d5f9 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libFreeCADGui.so+0x89
realthunder/FreeCAD_assembly3#54  0x7f1dbb4b2606 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Core.so.5+0x86
realthunder/FreeCAD_assembly3#55  0x7f1dbb4b283e in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Core.so.5+0x1da
realthunder/FreeCAD_assembly3#56  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Core.so.5(+0x1dc54c) [0x7f1dbb4e154c]
realthunder/FreeCAD_assembly3#57  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/./libglib-2.0.so.0(g_main_context_dispatch+0x27d) [0x7f1db7afa76d]
realthunder/FreeCAD_assembly3#58  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/./libglib-2.0.so.0(+0x56a01) [0x7f1db7afaa01]
realthunder/FreeCAD_assembly3#59  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/./libglib-2.0.so.0(g_main_context_iteration+0x31) [0x7f1db7afaaa1]
realthunder/FreeCAD_assembly3#60  0x7f1dbb4e10e8 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Core.so.5+0x5e
realthunder/FreeCAD_assembly3#61  0x7f1dbb4af019 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Core.so.5+0x187
realthunder/FreeCAD_assembly3#62  0x7f1dbc05b8d9 in QDialog::exec() from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x11d
realthunder/FreeCAD_assembly3#63  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5(+0x2d8c71) [0x7f1dbc07ec71]
realthunder/FreeCAD_assembly3#64  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libFreeCADGui.so(+0x4b6f22) [0x7f1dbd1c8f22]
realthunder/FreeCAD_assembly3#65  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libFreeCADApp.so(+0x382bb4) [0x7f1dbc66cbb4]
realthunder/FreeCAD_assembly3#66  0x7f1dbc7a9b5a in App::Application::openDocuments(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*, bool) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libFreeCADApp.so+0x1bda
realthunder/FreeCAD_assembly3#67  0x7f1dbc7aa578 in App::Application::openDocument(char const*, bool) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libFreeCADApp.so+0xc8
realthunder/FreeCAD_assembly3#68  0x7f1dbc7b4508 in App::Application::sOpenDocument(_object*, _object*, _object*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libFreeCADApp.so+0xe8
realthunder/FreeCAD_assembly3#69  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libpython3.9.so.1.0(+0x146f75) [0x7f1dbcac4f75]
realthunder/FreeCAD_assembly3#70  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libpython3.9.so.1.0(_PyObject_MakeTpCall+0x286) [0x7f1dbcab3dc6]
realthunder/FreeCAD_assembly3#71  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libpython3.9.so.1.0(_PyEval_EvalFrameDefault+0x5123) [0x7f1dbcab0e43]
realthunder/FreeCAD_assembly3#72  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libpython3.9.so.1.0(+0x12cf99) [0x7f1dbcaaaf99]
realthunder/FreeCAD_assembly3#73  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libpython3.9.so.1.0(_PyEval_EvalCodeWithName+0x51) [0x7f1dbcaaac51]
realthunder/FreeCAD_assembly3#74  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libpython3.9.so.1.0(PyEval_EvalCodeEx+0x3a) [0x7f1dbcaaabfa]
realthunder/FreeCAD_assembly3#75  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libpython3.9.so.1.0(PyEval_EvalCode+0x1c) [0x7f1dbcb3d46c]
realthunder/FreeCAD_assembly3#76  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libpython3.9.so.1.0(+0x1edaaf) [0x7f1dbcb6baaf]
realthunder/FreeCAD_assembly3#77  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libpython3.9.so.1.0(+0x1e9b0c) [0x7f1dbcb67b0c]
realthunder/FreeCAD_assembly3#78  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libpython3.9.so.1.0(PyRun_StringFlags+0xa7) [0x7f1dbcb5f567]
realthunder/FreeCAD_assembly3#79  0x7f1dbb85c87c in Base::InterpreterSingleton::runString[abi:cxx11](char const*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libFreeCADBase.so+0x6c
realthunder/FreeCAD_assembly3#80  0x7f1dbd2e1305 in Gui::Command::_runCommand(char const*, int, Gui::Command::DoCmd_Type, char const*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libFreeCADGui.so+0x95
realthunder/FreeCAD_assembly3#81  0x7f1dbd2e14b1 in Gui::Command::_doCommand(char const*, int, Gui::Command::DoCmd_Type, char const*, ...) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libFreeCADGui.so+0x101
realthunder/FreeCAD_assembly3#82  0x7f1dbd1c6535 in Gui::Application::open(char const*, char const*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libFreeCADGui.so+0x435
realthunder/FreeCAD_assembly3#83  0x7f1dbd2be877 in Gui::RecentFilesAction::activateFile(int) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libFreeCADGui.so+0x257
realthunder/FreeCAD_assembly3#84  0x7f1dbd2ead38 in Gui::Command::_invoke(int, bool) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libFreeCADGui.so+0x288
realthunder/FreeCAD_assembly3#85  0x7f1dbd2eb1e6 in Gui::Command::invoke(int, Gui::Command::TriggerSource) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libFreeCADGui.so+0x146
realthunder/FreeCAD_assembly3#86  0x7f1dbb4c8a18 in QMetaObject::activate(QObject*, int, int, void**) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Core.so.5+0x6c0
realthunder/FreeCAD_assembly3#87  0x7f1dbbf18283 in QActionGroup::triggered(QAction*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x2f
realthunder/FreeCAD#330  0x7f1dbb4c8a18 in QMetaObject::activate(QObject*, int, int, void**) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Core.so.5+0x6c0
realthunder/FreeCAD_assembly3#89  0x7f1dbbf15928 in QAction::triggered(bool) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x32
realthunder/FreeCAD_assembly3#90  0x7f1dbbf172b2 in QAction::activate(QAction::ActionEvent) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0xc6
realthunder/FreeCAD_assembly3#91  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5(+0x263653) [0x7f1dbc009653]
realthunder/FreeCAD_assembly3#92  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5(+0x2681a2) [0x7f1dbc00e1a2]
realthunder/FreeCAD_assembly3#93  0x7f1dbc00e900 in QMenu::mouseReleaseEvent(QMouseEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0xbc
realthunder/FreeCAD_assembly3#94  0x7f1dbbf454ed in QWidget::event(QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x133
realthunder/FreeCAD_assembly3#95  0x7f1dbc00ffac in QMenu::event(QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x2d0
realthunder/FreeCAD_assembly3#96  0x7f1dbbf1a7f2 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0xdc
realthunder/FreeCAD_assembly3#97  0x7f1dbbf1ef5e in QApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x70a
realthunder/FreeCAD_assembly3#98  0x7f1dbd27d5f9 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libFreeCADGui.so+0x89
realthunder/FreeCAD_assembly3#99  0x7f1dbb4b2606 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Core.so.5+0x86
realthunder/FreeCAD_assembly3#100  0x7f1dbbf1e4c4 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x286
realthunder/FreeCAD_assembly3#101  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5(+0x1aea9d) [0x7f1dbbf54a9d]
realthunder/FreeCAD_assembly3#102  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5(+0x1aff7c) [0x7f1dbbf55f7c]
realthunder/FreeCAD_assembly3#103  0x7f1dbbf1a7f2 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0xdc
realthunder/FreeCAD_assembly3#104  0x7f1dbbf2031d in QApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x1ac9
realthunder/FreeCAD_assembly3#105  0x7f1dbd27d5f9 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libFreeCADGui.so+0x89
realthunder/FreeCAD_assembly3#106  0x7f1dbb4b2606 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Core.so.5+0x86
realthunder/FreeCAD_assembly3#107  0x7f1dbba98ec5 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Gui.so.5+0x677
realthunder/FreeCAD_assembly3#108  0x7f1dbba9991f in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Gui.so.5+0x5f
realthunder/FreeCAD_assembly3#109  0x7f1dbba86c65 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Gui.so.5+0x63
realthunder/FreeCAD_assembly3#110  /tmp/.mount_FreeCAzCh8uD/usr/plugins/platforms/../../lib/libQt5XcbQpa.so.5(+0x5b010) [0x7f1db21f1010]
realthunder/FreeCAD_assembly3#111  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/./libglib-2.0.so.0(g_main_context_dispatch+0x27d) [0x7f1db7afa76d]
realthunder/FreeCAD_assembly3#112  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/./libglib-2.0.so.0(+0x56a01) [0x7f1db7afaa01]
realthunder/FreeCAD_assembly3#113  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/./libglib-2.0.so.0(g_main_context_iteration+0x31) [0x7f1db7afaaa1]
realthunder/FreeCAD_assembly3#114  0x7f1dbb4e10e8 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Core.so.5+0x5e
realthunder/FreeCAD_assembly3#115  0x7f1dbb4af019 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Core.so.5+0x187
realthunder/FreeCAD_assembly3#116  0x7f1dbb4b2e8f in QCoreApplication::exec() from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Core.so.5+0xfd
realthunder/FreeCAD_assembly3#117  0x7f1dbd1ec563 in Gui::Application::runApplication() from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libFreeCADGui.so+0x443
realthunder/FreeCAD_assembly3#118  /tmp/.mount_FreeCAzCh8uD/usr/bin/FreeCADLink(+0x470d) [0x55a47e9d270d]
realthunder/FreeCAD_assembly3#119  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xcd) [0x7f1dbaf597fd]
realthunder/FreeCAD_assembly3#120  /tmp/.mount_FreeCAzCh8uD/usr/bin/FreeCADLink(+0x4aa9) [0x55a47e9d2aa9]
```

> OS: Debian GNU/Linux bookworm/sid (X-Cinnamon/cinnamon)
> Word size of FreeCAD: 64-bit
> Version: 2022.430.26244 +4758 (Git) AppImage
> Build type: Release
> Branch: LinkDaily
> Hash: b024b876480a533018fdc702145e9e38f8c54ba6
> Python version: 3.9.12
> Qt version: 5.12.9
> Coin version: 4.0.1
> OCC version: 7.5.3
> Locale: Dutch/Netherlands (nl_NL)
> 

![IMG_20220603_181153_873](https://user-images.githubusercontent.com/1257901/171991938-7989edf2-f9c0-4308-82c8-39ae47946121.jpeg)
[EinhellRails.FCStd.txt](https://github.com/realthunder/FreeCAD_assembly3/files/8837316/EinhellRails.FCStd.txt)

**Comment by luzpaz** [comment]
Side note: please use code tags when posting errors since hashtags + numbers will trigger an auto-linking to another github ticket.  I've modified the OP to fix that.
