### ISSUE TITLE
Crash when opening 8devices mango board step file

### ISSUE THREAD

**Issue by CharlemagneLasse** [realthunder/FreeCAD#476]
I've just tried to open the STEP file from https://www.8devices.com/media/products/mango/downloads/MAN200_04-DVK-2021-11-18.zip with [FreeCAD-asm3-Daily-Conda-Py3-Qt5-20220704-glibc2.12-x86_64.AppImage](https://github.com/realthunder/FreeCAD/releases/download/2022.07.04-edge/FreeCAD-asm3-Daily-Conda-Py3-Qt5-20220704-glibc2.12-x86_64.AppImage)

```
OS: Debian GNU/Linux 11 (bullseye) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 2022.704.26244 +4971 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: a87320cc64699a8e4226bad2e9b37ac3a1296ab9
Python version: 3.9.13
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.3
Locale: English/United States (en_US)
```

When it started to show the various parts, it crashed:

````
FreeCAD 0.20, Libs: 2022.704R26244 +4971 (Git)
<Import> ImportOCAF2.cpp(690): free shape count 33
Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libc.so.6(+0x3bd60) [0x7ffff4d74d60]
#1  0x7fffdac808c6 in Import::ImportOCAF2::expandShape(App::Document*, TDF_Label, TopoDS_Shape const&, Import::ImportOCAF2::ColorInfo&) from /tmp/.mount_freeca6z71ud/usr/lib/./Import.so+0xa56
#2  0x7fffdac7fc67 in Import::ImportOCAF2::createObject(App::Document*, TDF_Label, TopoDS_Shape const&, Import::ImportOCAF2::Info&, bool) from /tmp/.mount_freeca6z71ud/usr/lib/./Import.so+0xd47
#3  0x7fffdac8392e in Import::ImportOCAF2::loadShape(App::Document*, TDF_Label, TopoDS_Shape const&, bool, bool) from /tmp/.mount_freeca6z71ud/usr/lib/./Import.so+0x2ee
#4  0x7fffdac81bb3 in Import::ImportOCAF2::createAssembly(App::Document*, TDF_Label, TopoDS_Shape const&, Import::ImportOCAF2::Info&, bool) from /tmp/.mount_freeca6z71ud/usr/lib/./Import.so+0x243
#5  0x7fffdac83db5 in Import::ImportOCAF2::loadShape(App::Document*, TDF_Label, TopoDS_Shape const&, bool, bool) from /tmp/.mount_freeca6z71ud/usr/lib/./Import.so+0x775
#6  0x7fffdac848b6 in Import::ImportOCAF2::loadShapes() from /tmp/.mount_freeca6z71ud/usr/lib/./Import.so+0x526
#7  /tmp/.mount_freeca6z71ud/usr/lib/ImportGui.so(+0x236f5) [0x7fffe81366f5]
#8  /tmp/.mount_freeca6z71ud/usr/lib/ImportGui.so(+0x176bd) [0x7fffe812a6bd]
#9  /tmp/.mount_freeca6z71ud/usr/bin/../lib/libFreeCADBase.so(method_keyword_call_handler+0x374) [0x7ffff562bcf4]
#10  /tmp/.mount_freeca6z71ud/usr/bin/../lib/libpython3.9.so.1.0(+0x147085) [0x7ffff68d3085]
#11  /tmp/.mount_freeca6z71ud/usr/bin/../lib/libpython3.9.so.1.0(_PyObject_MakeTpCall+0x286) [0x7ffff68c1e76]
#12  /tmp/.mount_freeca6z71ud/usr/bin/../lib/libpython3.9.so.1.0(_PyEval_EvalFrameDefault+0x5120) [0x7ffff68beed0]
#13  /tmp/.mount_freeca6z71ud/usr/bin/../lib/libpython3.9.so.1.0(+0x12d029) [0x7ffff68b9029]
#14  /tmp/.mount_freeca6z71ud/usr/bin/../lib/libpython3.9.so.1.0(_PyEval_EvalCodeWithName+0x51) [0x7ffff68b8ce1]
#15  /tmp/.mount_freeca6z71ud/usr/bin/../lib/libpython3.9.so.1.0(PyEval_EvalCodeEx+0x3a) [0x7ffff68b8c8a]
#16  /tmp/.mount_freeca6z71ud/usr/bin/../lib/libpython3.9.so.1.0(PyEval_EvalCode+0x1c) [0x7ffff694b32c]
#17  /tmp/.mount_freeca6z71ud/usr/bin/../lib/libpython3.9.so.1.0(+0x1eda9f) [0x7ffff6979a9f]
#18  /tmp/.mount_freeca6z71ud/usr/bin/../lib/libpython3.9.so.1.0(+0x1e9adc) [0x7ffff6975adc]
#19  /tmp/.mount_freeca6z71ud/usr/bin/../lib/libpython3.9.so.1.0(PyRun_StringFlags+0xa7) [0x7ffff696d517]
#20  0x7ffff565f0cc in Base::InterpreterSingleton::runString[abi:cxx11](char const*) from /tmp/.mount_freeca6z71ud/usr/bin/../lib/libFreeCADBase.so+0x6c
#21  0x7ffff56606f0 in Base::InterpreterSingleton::runStringArg(char const*, ...) from /tmp/.mount_freeca6z71ud/usr/bin/../lib/libFreeCADBase.so+0xd0
#22  0x7ffff65b5746 in App::Application::processFiles(std::__cxx11::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) from /tmp/.mount_freeca6z71ud/usr/bin/../lib/libFreeCADApp.so+0x366
#23  0x7ffff76350ba in Gui::MainWindow::delayedStartup() from /tmp/.mount_freeca6z71ud/usr/bin/../lib/libFreeCADGui.so+0xaa
#24  0x7ffff52c8f16 in QObject::event(QEvent*) from /tmp/.mount_freeca6z71ud/usr/bin/../lib/libQt5Core.so.5+0xbc
#25  0x7ffff5d440af in QWidget::event(QEvent*) from /tmp/.mount_freeca6z71ud/usr/bin/../lib/libQt5Widgets.so.5+0xcc5
#26  0x7ffff5dee385 in QMainWindow::event(QEvent*) from /tmp/.mount_freeca6z71ud/usr/bin/../lib/libQt5Widgets.so.5+0xdd
#27  0x7ffff5d18822 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_freeca6z71ud/usr/bin/../lib/libQt5Widgets.so.5+0xdc
#28  0x7ffff5d1e34d in QApplication::notify(QObject*, QEvent*) from /tmp/.mount_freeca6z71ud/usr/bin/../lib/libQt5Widgets.so.5+0x1ac9
#29  0x7ffff709a3b9 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_freeca6z71ud/usr/bin/../lib/libFreeCADGui.so+0x89
#30  0x7ffff52b3f88 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_freeca6z71ud/usr/bin/../lib/libQt5Core.so.5+0x86
#31  0x7ffff52b41c0 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) from /tmp/.mount_freeca6z71ud/usr/bin/../lib/libQt5Core.so.5+0x1da
#32  0x7ffff52e0bc1 in QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_freeca6z71ud/usr/bin/../lib/libQt5Core.so.5+0x33
#33  /tmp/.mount_freeca6z71ud/usr/plugins/platforms/../../lib/libQt5XcbQpa.so.5(+0x59ef4) [0x7fffec109ef4]
#34  0x7ffff52b099b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_freeca6z71ud/usr/bin/../lib/libQt5Core.so.5+0x187
#35  0x7ffff52b4811 in QCoreApplication::exec() from /tmp/.mount_freeca6z71ud/usr/bin/../lib/libQt5Core.so.5+0xfd
#36  0x7ffff700b71b in Gui::Application::runApplication() from /tmp/.mount_freeca6z71ud/usr/bin/../lib/libFreeCADGui.so+0x44b
#37  /tmp/.mount_freeca6z71ud/usr/bin/FreeCADLink(+0x4659) [0x555555558659]
#38  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xea) [0x7ffff4d5fd0a]
#39  /tmp/.mount_freeca6z71ud/usr/bin/FreeCADLink(+0x49e9) [0x5555555589e9]
````

It worked fine with https://github.com/FreeCAD/FreeCAD/releases/download/0.20/FreeCAD-0.20.0-Linux-x86_64.AppImage

```
OS: Debian GNU/Linux 11 (bullseye) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.29177 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0.20)
Hash: 68e337670e227889217652ddac593c93b5e8dc94
Python 3.9.13, Qt 5.12.9, Coin 4.0.0, Vtk 9.1.0, OCC 7.5.3
Locale: English/United States (en_US)
Installed mods: 
  * SelectorToolbar
```

**Comment by realthunder** [comment]
Fixed in above commit. Before the next release, you can work around it by disable the following option

![image](https://user-images.githubusercontent.com/1207888/178017941-504c90dd-0517-47ed-ab58-ecc4ca091182.png)
