### ISSUE TITLE
Sheet Metal WB not unfolding correctly in LinkStage3

### ISSUE THREAD

**Issue by thesonnenberg** [realthunder/FreeCAD#533]
when trying to unwrap a sheet metal object the following error occurs and no sketch with bend lines is generated  
```
Traceback (most recent call last):
  File "/home/xxxxx/snap/freecad-realthunder/common/.FreeCAD/Mod/sheetmetal/SheetMetalUnfolder.py", line 2899, in accept
    grp1 = TechDraw.projectEx(s,norm)
<class 'AttributeError'>: module 'TechDraw' has no attribute 'projectEx'
```

I could not recreate the same error with the FreeCAD 0.20 main branch, that is why my assumption is that it is not necessarily a Sheet Metal WB issue but might be related to the LinkStage3 branch.

attached the screenshots from the LinkStage3 branch when the error occurred.

**System/SW used:**
OS: Ubuntu Core 20 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 2022.801.14555 (Git shallow)
Build type: Release
Branch: (HEAD detached at 2022.08.01-edge)
Hash: 1a5c42ee6bd3e32e3dfee8f659349546d217569a
Python version: 3.8.10
Qt version: 5.15.3
Coin version: 4.0.1
OCC version:
 7.6.2
Locale: English/United States (en_US)

![Screenshot1](https://user-images.githubusercontent.com/108614550/184667032-4994f6f6-3e75-4b85-a9b1-2a7cbe9bc1d0.png)
![Screenshot2](https://user-images.githubusercontent.com/108614550/184667023-53de2099-e1b8-4f26-9f77-bdbf3a099bd0.png)

**Comment by stuartpittaway** [comment]
I've also got the same issue on Windows using the version FreeCAD-asm3-Daily-Win64-Py3-Qt5-20220709

```
Engineering mode is not enabled.
20:18:34  Manual K-factor is being used: 0.40 (ansi)
20:18:34  Traceback (most recent call last):
  File "C:\Users\Stuart\AppData\Roaming\FreeCAD\Mod\sheetmetal\SheetMetalUnfolder.py", line 2899, in accept
    grp1 = TechDraw.projectEx(s,norm)
<class 'AttributeError'>: module 'TechDraw' has no attribute 'projectEx'
```

```
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 2022.709.26244 +5001 (Git)
Build type: Release
Branch: LinkDaily
Hash: 096210d21183e9dfdc3b25777760bfb6c00a210b
Python version: 3.8.10
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.6.2
Locale: English/United Kingdom (en_GB)
```

**Comment by luzpaz** [comment]
@realthunder is this asm3 or link related ?
