### ISSUE TITLE
FreeCAD crashes

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD#542]
# Description

This is a reproducible error. When I try to move a part into an `Object_Group`, FreeCAD crashes. 

https://user-images.githubusercontent.com/6639874/185862841-d9f5c5d1-d920-4713-ae98-192d1ffb388c.mp4

# Attachment 

Latest project that I sent privately can be used, they are the same projects. 

# Traceback

```
Coin error in SoSensorManager::processDelayQueue(): Unexpected function exit. Unhandled Exception?
Coin error in SoSensorManager::processTimerQueue(): Unexpected function exit. Unhandled Exception?
Unhandled unknown exception caught in GUIApplication::notify.
SoFCUnifiedSelection.cpp(2460): Cyclic scene graph:
0x55ce0a20ae00, housing2#Assembly
0x55ce0a20bba0
0x55ce103a03c0, housing2#Parts
0x55ce0a2180c0
0x55ce0a20ae00, housing2#Assembly
Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libpthread.so.0(+0x12730) [0x7f33500a1730]
Segmentation fault

```

# Version 

```
OS: Debian GNU/Linux 10 (buster)
Word size of FreeCAD: 64-bit
Version: 0.20.31376 (Git)
Build type: Release
Branch: LinkDaily
Hash: 4af956063635ef77f68618cf6f15b4f77c9b6240
Python version: 3.7.3
Qt version: 5.11.3
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/UnitedStates (en_US)
```

**Comment by ceremcem** [comment]
Reproducing the crash generated a slightly different output: 

```
Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libpthread.so.0(+0x12730) [0x7f6268024730]
#1  0x7f626a537c50 in typeinfo name for SoGetMatrixAction from /lib/x86_64-linux-gnu/libCoin.so.80c+0
```

**Comment by ceremcem** [comment]
Reproducing the crash generated a way different output: 

```
Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libpthread.so.0(+0x12730) [0x7f785030b730]
#1  0x7f785261a096 in SoType::getData() const from /lib/x86_64-linux-gnu/libCoin.so.80c+0x16
#2  0x7f7852656c53 in SoNode::getActionMethodIndex(SoType) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x13
#3  0x7f785247b661 in SoAction::traverse(SoNode*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x31
#4  0x7f7852605208 in SoChildList::traverse(SoAction*, int, int) from /lib/x86_64-linux-gnu/libCoin.so.80c+0xe8
#5  0x7f785264dc63 in SoGroup::getBoundingBox(SoGetBoundingBoxAction*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0xb3
#6  0x7f785266739e in SoSeparator::getBoundingBox(SoGetBoundingBoxAction*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x1de
#7  0x7f7853ae219f in Gui::SoFCSelectionRoot::getBoundingBox(SoGetBoundingBoxAction*) from /home/aea/fc-build/Release/lib/libFreeCADGui.so+0x6f
#8  0x7f7852656828 in SoNode::getBoundingBoxS(SoAction*, SoNode*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x48
#9  0x7f785247b694 in SoAction::traverse(SoNode*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x64
#10  0x7f7852605208 in SoChildList::traverse(SoAction*, int, int) from /lib/x86_64-linux-gnu/libCoin.so.80c+0xe8
#11  0x7f785266a79f in SoSwitch::doAction(SoAction*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x26f
#12  0x7f7853ac137c in SoFCSwitch::doAction(SoAction*) from /home/aea/fc-build/Release/lib/libFreeCADGui.so+0x4bc
#13  0x7f7852656828 in SoNode::getBoundingBoxS(SoAction*, SoNode*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x48
#14  0x7f785247b694 in SoAction::traverse(SoNode*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x64
#15  0x7f7852605208 in SoChildList::traverse(SoAction*, int, int) from /lib/x86_64-linux-gnu/libCoin.so.80c+0xe8
#16  0x7f785264dc63 in SoGroup::getBoundingBox(SoGetBoundingBoxAction*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0xb3
#17  0x7f785266739e in SoSeparator::getBoundingBox(SoGetBoundingBoxAction*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x1de
#18  0x7f7853ae219f in Gui::SoFCSelectionRoot::getBoundingBox(SoGetBoundingBoxAction*) from /home/aea/fc-build/Release/lib/libFreeCADGui.so+0x6f
#19  0x7f7852656828 in SoNode::getBoundingBoxS(SoAction*, SoNode*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x48
#20  0x7f785247b694 in SoAction::traverse(SoNode*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x64
#21  0x7f7852605208 in SoChildList::traverse(SoAction*, int, int) from /lib/x86_64-linux-gnu/libCoin.so.80c+0xe8
#22  0x7f785266a79f in SoSwitch::doAction(SoAction*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x26f
#23  0x7f7853ac137c in SoFCSwitch::doAction(SoAction*) from /home/aea/fc-build/Release/lib/libFreeCADGui.so+0x4bc
#24  0x7f7852656828 in SoNode::getBoundingBoxS(SoAction*, SoNode*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x48
#25  0x7f785247b694 in SoAction::traverse(SoNode*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x64
#26  0x7f7852605208 in SoChildList::traverse(SoAction*, int, int) from /lib/x86_64-linux-gnu/libCoin.so.80c+0xe8
#27  0x7f785264dc63 in SoGroup::getBoundingBox(SoGetBoundingBoxAction*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0xb3
#28  0x7f785266739e in SoSeparator::getBoundingBox(SoGetBoundingBoxAction*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x1de
#29  0x7f7853ae219f in Gui::SoFCSelectionRoot::getBoundingBox(SoGetBoundingBoxAction*) from /home/aea/fc-build/Release/lib/libFreeCADGui.so+0x6f
#30  0x7f7852656828 in SoNode::getBoundingBoxS(SoAction*, SoNode*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x48
#31  0x7f785247b694 in SoAction::traverse(SoNode*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x64
#32  0x7f7852605208 in SoChildList::traverse(SoAction*, int, int) from /lib/x86_64-linux-gnu/libCoin.so.80c+0xe8
#33  0x7f785266a79f in SoSwitch::doAction(SoAction*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x26f
#34  0x7f7853ac137c in SoFCSwitch::doAction(SoAction*) from /home/aea/fc-build/Release/lib/libFreeCADGui.so+0x4bc
#35  0x7f7852656828 in SoNode::getBoundingBoxS(SoAction*, SoNode*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x48
#36  0x7f785247b694 in SoAction::traverse(SoNode*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x64
#37  0x7f7852605208 in SoChildList::traverse(SoAction*, int, int) from /lib/x86_64-linux-gnu/libCoin.so.80c+0xe8
#38  0x7f785264dc63 in SoGroup::getBoundingBox(SoGetBoundingBoxAction*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0xb3
#39  0x7f785266739e in SoSeparator::getBoundingBox(SoGetBoundingBoxAction*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x1de
#40  0x7f7853ae219f in Gui::SoFCSelectionRoot::getBoundingBox(SoGetBoundingBoxAction*) from /home/aea/fc-build/Release/lib/libFreeCADGui.so+0x6f
#41  0x7f7852656828 in SoNode::getBoundingBoxS(SoAction*, SoNode*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x48
#42  0x7f785247b694 in SoAction::traverse(SoNode*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x64
#43  0x7f7852605208 in SoChildList::traverse(SoAction*, int, int) from /lib/x86_64-linux-gnu/libCoin.so.80c+0xe8
#44  0x7f785264dc63 in SoGroup::getBoundingBox(SoGetBoundingBoxAction*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0xb3
#45  0x7f785266739e in SoSeparator::getBoundingBox(SoGetBoundingBoxAction*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x1de
#46  0x7f7853adac3a in Gui::SoFCUnifiedSelection::getBoundingBox(SoGetBoundingBoxAction*) from /home/aea/fc-build/Release/lib/libFreeCADGui.so+0x5a
#47  0x7f7852656828 in SoNode::getBoundingBoxS(SoAction*, SoNode*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x48
#48  0x7f785247b694 in SoAction::traverse(SoNode*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x64
#49  0x7f7852605208 in SoChildList::traverse(SoAction*, int, int) from /lib/x86_64-linux-gnu/libCoin.so.80c+0xe8
#50  0x7f785264dc63 in SoGroup::getBoundingBox(SoGetBoundingBoxAction*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0xb3
#51  0x7f785266739e in SoSeparator::getBoundingBox(SoGetBoundingBoxAction*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x1de
#52  0x7f7852656828 in SoNode::getBoundingBoxS(SoAction*, SoNode*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x48
#53  0x7f785247b694 in SoAction::traverse(SoNode*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x64
#54  0x7f785247bc22 in SoAction::apply(SoNode*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x372
#55  0x7f78527288ee in SoRenderManagerP::setClippingPlanes() from /lib/x86_64-linux-gnu/libCoin.so.80c+0x8e
#56  0x7f78527550e9 in SoDataSensor::trigger() from /lib/x86_64-linux-gnu/libCoin.so.80c+0x9
#57  0x7f7852756b46 in SoSensorManager::processDelayQueue(int) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x276
#58  0x7f785275609f in SoSensorManager::processTimerQueue() from /lib/x86_64-linux-gnu/libCoin.so.80c+0xdf
#59  0x7f7853b753a1 in SIM::Coin3D::Quarter::SensorManager::delayTimeout() from /home/aea/fc-build/Release/lib/libFreeCADGui.so+0x11
#60  0x7f7850b477f6 in QMetaObject::activate(QObject*, int, int, void**) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x766
#61  0x7f7850b53387 in QTimer::timeout(QTimer::QPrivateSignal) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x37
#62  0x7f7850b4802b in QObject::event(QEvent*) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x9b
#63  0x7f78516d34c1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x81
#64  0x7f78516da970 in QApplication::notify(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x210
#65  0x7f78537c3488 in Gui::GUIApplication::notify(QObject*, QEvent*) from /home/aea/fc-build/Release/lib/libFreeCADGui.so+0x68
#66  0x7f7850b1e489 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x179
#67  0x7f7850b6eb38 in QTimerInfoList::activateTimers() from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x428
#68  /lib/x86_64-linux-gnu/libQt5Core.so.5(+0x2bb394) [0x7f7850b6f394]
#69  /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x2ae) [0x7f784e0d8f2e]
#70  /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x4e1c8) [0x7f784e0d91c8]
#71  /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x2c) [0x7f784e0d925c]
#72  0x7f7850b6f727 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x67
#73  /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5(+0xdd491) [0x7f7846228491]
#74  0x7f7850b1d15b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x13b
#75  0x7f7850b25132 in QCoreApplication::exec() from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x92
#76  0x7f785372e85f in Gui::Application::runApplication() from /home/aea/fc-build/Release/lib/libFreeCADGui.so+0x32f
#77  /home/aea/fc-build/Release/bin/FreeCAD(+0x584a) [0x56175092184a]
#78  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7f784f6ee09b]
#79  /home/aea/fc-build/Release/bin/FreeCAD(+0x5c3a) [0x561750921c3a]
```
