### ISSUE TITLE
split to boolean fail

### ISSUE THREAD

**Issue by dulouie** [realthunder/FreeCAD#64]
The boolean feature has a wrong shape, look at the attached file.
[booleanSplit_fail.zip](https://github.com/realthunder/FreeCAD/files/5501990/booleanSplit_fail.zip)

**Comment by dulouie** [comment]
And increasing the Extrusion plane length cause crash.

**Comment by realthunder** [comment]
The split failure is most likely an OCC problem. You can see that the split is not correct near the seam edge of the cylinder. You can work around this by split at a different angle, avoiding the seam edge.

![Screenshot from 2020-11-08 21-11-57](https://user-images.githubusercontent.com/1207888/98465953-6801dc80-2207-11eb-8e1d-24b9b3d3dc25.png)

I can't reproduce the crash reliably. I did fix a crash problem related to rendering. Not sure if this is the crash you experienced. Did you have any stack trace when it crashed?

**Comment by dulouie** [comment]
At 153b298a1cb52f5040fdc0ac371173586d2a2686 increasing and decreasing the length of the extrusion multiple times i get this crash log.

> Tried to run Gui::Application::initApplication() twice!
```
<Command> Command.cpp(1839): duplicate command Std_TreePreSelection
<Command> Command.cpp(1839): duplicate command Std_TreeSelectAllInstances
connect failed: Datei oder Verzeichnis nicht gefunden
<Exception> ShapeBinder.cpp(489): Missing support object
Recompute failed! Please check report view.
<Exception> ShapeBinder.cpp(489): Missing support object
Recompute failed! Please check report view.
<Exception> ShapeBinder.cpp(489): Missing support object
Recompute failed! Please check report view.
<Exception> ShapeBinder.cpp(489): Missing support object
Recompute failed! Please check report view.
<Exception> ShapeBinder.cpp(489): Missing support object
Recompute failed! Please check report view.
Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f0b45cb4210]
#1  /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so(+0x2c6f35) [0x7f0b32c48f35]
#2  0x7f0a9a534f52 in PartGui::SoBrepFaceSet::renderFaces(SoCoordinateElement const*, int const*, int, int const*, int, int, SbVec3f const*, int const*, SoMaterialBundle*, int const*, SoTextureCoordinateBundle&, int const*, int, int, int) from /home/arne/src/LinkStage3/build/Mod/Part/PartGui.so+0x1302
#3  0x7f0a9a539df3 in PartGui::SoBrepFaceSet::renderShape(SoGLRenderAction*) from /home/arne/src/LinkStage3/build/Mod/Part/PartGui.so+0x363
#4  0x7f0a9a53bcd8 in PartGui::SoBrepFaceSet::renderShape(SoGLRenderAction*, std::shared_ptr<Gui::SoFCSelectionContextEx>, std::shared_ptr<Gui::SoFCSelectionContextEx>, bool, bool) from /home/arne/src/LinkStage3/build/Mod/Part/PartGui.so+0x3f8
#5  0x7f0a9a53dace in PartGui::SoBrepFaceSet::glRender(SoGLRenderAction*, bool) from /home/arne/src/LinkStage3/build/Mod/Part/PartGui.so+0x17ee
#6  0x7f0b458aad02 in SoSeparator::GLRenderBelowPath(SoGLRenderAction*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x3d2
#7  0x7f0b458aad02 in SoSeparator::GLRenderBelowPath(SoGLRenderAction*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x3d2
#8  0x7f0b456af277 in SoAction::traverse(SoNode*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x67
#9  0x7f0b458464d8 in SoChildList::traverse(SoAction*, int, int) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x168
#10  0x7f0b4890ae1f in Gui::SoFCSwitch::doAction(SoAction*) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0x75f
#11  0x7f0b458aa1ce in SoSeparator::GLRenderInPath(SoGLRenderAction*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x4be
#12  0x7f0b48909b6e in Gui::SoFCSelectionRoot::_renderPrivate(SoGLRenderAction*, bool, bool&) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0x8ae
#13  0x7f0b4890a0b4 in Gui::SoFCSelectionRoot::renderPrivate(SoGLRenderAction*, bool) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0xd4
#14  0x7f0b4589144a in SoGroup::GLRender(SoGLRenderAction*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0xca
#15  0x7f0b456af277 in SoAction::traverse(SoNode*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x67
#16  0x7f0b458463f7 in SoChildList::traverse(SoAction*, int, int) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x87
#17  0x7f0b4890abd5 in Gui::SoFCSwitch::doAction(SoAction*) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0x515
#18  0x7f0b458aa1ce in SoSeparator::GLRenderInPath(SoGLRenderAction*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x4be
#19  0x7f0b48909b6e in Gui::SoFCSelectionRoot::_renderPrivate(SoGLRenderAction*, bool, bool&) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0x8ae
#20  0x7f0b4890a0b4 in Gui::SoFCSelectionRoot::renderPrivate(SoGLRenderAction*, bool) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0xd4
#21  0x7f0b458aa1ce in SoSeparator::GLRenderInPath(SoGLRenderAction*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x4be
#22  0x7f0b48909b6e in Gui::SoFCSelectionRoot::_renderPrivate(SoGLRenderAction*, bool, bool&) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0x8ae
#23  0x7f0b4890a0b4 in Gui::SoFCSelectionRoot::renderPrivate(SoGLRenderAction*, bool) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0xd4
#24  0x7f0b456af277 in SoAction::traverse(SoNode*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x67
#25  0x7f0b458463f7 in SoChildList::traverse(SoAction*, int, int) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x87
#26  0x7f0b4890abd5 in Gui::SoFCSwitch::doAction(SoAction*) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0x515
#27  0x7f0b458aa1ce in SoSeparator::GLRenderInPath(SoGLRenderAction*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x4be
#28  0x7f0b48909b6e in Gui::SoFCSelectionRoot::_renderPrivate(SoGLRenderAction*, bool, bool&) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0x8ae
#29  0x7f0b4890a0b4 in Gui::SoFCSelectionRoot::renderPrivate(SoGLRenderAction*, bool) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0xd4
#30  0x7f0b458aa1ce in SoSeparator::GLRenderInPath(SoGLRenderAction*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x4be
#31  0x7f0b48906429 in Gui::SoFCPathAnnotation::GLRenderBelowPath(SoGLRenderAction*) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0x489
#32  0x7f0b458aa1ce in SoSeparator::GLRenderInPath(SoGLRenderAction*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x4be
#33  0x7f0b4890996c in Gui::SoFCSelectionRoot::_renderPrivate(SoGLRenderAction*, bool, bool&) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0x6ac
#34  0x7f0b4890a0b4 in Gui::SoFCSelectionRoot::renderPrivate(SoGLRenderAction*, bool) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0xd4
#35  0x7f0b456af277 in SoAction::traverse(SoNode*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x67
#36  0x7f0b458463f7 in SoChildList::traverse(SoAction*, int, int) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x87
#37  0x7f0b4890abd5 in Gui::SoFCSwitch::doAction(SoAction*) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0x515
#38  0x7f0b458aa1ce in SoSeparator::GLRenderInPath(SoGLRenderAction*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x4be
#39  0x7f0b458aa1ce in SoSeparator::GLRenderInPath(SoGLRenderAction*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x4be
#40  0x7f0b456af277 in SoAction::traverse(SoNode*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x67
#41  0x7f0b456b68a5 in SoGLRenderAction::beginTraversal(SoNode*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x185
#42  0x7f0b456aff11 in SoAction::apply(SoPathList const&, int) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x571
#43  0x7f0b48914806 in Gui::SoBoxSelectionRenderAction::apply(SoPathList const&, int) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0x116
#44  0x7f0b456b611d in SoGLRenderActionP::renderSingle(SoNode*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x26d
#45  0x7f0b456b65c3 in SoGLRenderActionP::render(SoNode*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x113
#46  0x7f0b456b67c3 in SoGLRenderAction::beginTraversal(SoNode*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0xa3
#47  0x7f0b456af71a in SoAction::apply(SoNode*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x28a
#48  0x7f0b48917ded in Gui::SoBoxSelectionRenderAction::apply(SoNode*) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0x2d
#49  0x7f0b4596f3ed in SoRenderManager::renderScene(SoGLRenderAction*, SoNode*, unsigned int) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x4d
#50  0x7f0b45970573 in SoRenderManager::actuallyRender(SoGLRenderAction*, int, int, int) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x73
#51  0x7f0b45970712 in SoRenderManager::renderSingle(SoGLRenderAction*, int, int, int) from /lib/x86_64-linux-gnu/libCoin.so.80c+0xc2
#52  0x7f0b45970d51 in SoRenderManager::render(SoGLRenderAction*, int, int, int) from /lib/x86_64-linux-gnu/libCoin.so.80c+0xb1
#53  0x7f0b4596ebff in SoRenderManager::render(int, int) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x8f
#54  0x7f0b489da8a8 in Gui::View3DInventorViewer::renderScene() from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0x248
#55  0x7f0b489976fd in SIM::Coin3D::Quarter::QuarterWidget::paintEvent(QPaintEvent*) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0x30d
#56  0x7f0b4899f1f6 in SIM::Coin3D::Quarter::SoQTQuarterAdaptor::paintEvent(QPaintEvent*) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0x46
#57  0x7f0b46d3f2b6 in QWidget::event(QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x286
#58  0x7f0b46decd52 in QFrame::event(QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x22
#59  0x7f0b47057421 in QGraphicsView::viewportEvent(QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x161
#60  0x7f0b489977de in SIM::Coin3D::Quarter::QuarterWidget::viewportEvent(QEvent*) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0x9e
#61  0x7f0b462e264b in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x9b
#62  0x7f0b46cfca55 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x75
#63  0x7f0b46d060f0 in QApplication::notify(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x330
#64  0x7f0b48666918 in Gui::GUIApplication::notify(QObject*, QEvent*) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0x88
#65  0x7f0b462e293a in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x18a
#66  0x7f0b46d37f4a in QWidgetPrivate::sendPaintEvent(QRegion const&) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x3a
#67  /lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x17c732) [0x7f0b46d0e732]
#68  /lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x17cdc1) [0x7f0b46d0edc1]
#69  0x7f0b46d27385 in QWidgetPrivate::syncBackingStore() from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0xa5
#70  0x7f0b46d3fcac in QWidget::event(QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0xc7c
#71  0x7f0b46e54148 in QMainWindow::event(QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x68
#72  0x7f0b48aa53eb in Gui::MainWindow::event(QEvent*) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0x7b
#73  0x7f0b46cfca66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x86
#74  0x7f0b46d060f0 in QApplication::notify(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x330
#75  0x7f0b48666918 in Gui::GUIApplication::notify(QObject*, QEvent*) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0x88
#76  0x7f0b462e293a in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x18a
#77  0x7f0b462e55b8 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x148
#78  /lib/x86_64-linux-gnu/libQt5Core.so.5(+0x2def67) [0x7f0b4633af67]
#79  /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x27d) [0x7f0b43fa2fbd]
#80  /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x52240) [0x7f0b43fa3240]
#81  /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x7f0b43fa32e3]
#82  0x7f0b4633a565 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x65
#83  0x7f0b462e14db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x12b
#84  0x7f0b462e9246 in QCoreApplication::exec() from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x96
#85  0x7f0b485c0b0c in Gui::Application::runApplication() from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0x166c
#86  ./bin/FreeCAD(+0x4c8e) [0x5605fe84ac8e]
#87  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f0b45c950b3]
#88  ./bin/FreeCAD(+0x501e) [0x5605fe84b01e]
```

**Comment by dulouie** [comment]
With up-to-date branch at a386a1256ec3aa898f08a3bb0ca57e9dd8a62a9c i get also a crash after some time of fiddling with the extrusion length.

> Tried to run Gui::Application::initApplication() twice!
```
<Command> Command.cpp(1839): duplicate command Std_TreePreSelection
<Command> Command.cpp(1839): duplicate command Std_TreeSelectAllInstances
connect failed: Datei oder Verzeichnis nicht gefunden
<Exception> ShapeBinder.cpp(489): Missing support object
Recompute failed! Please check report view.
<Exception> ShapeBinder.cpp(489): Missing support object
Recompute failed! Please check report view.
<Exception> ShapeBinder.cpp(489): Missing support object
Recompute failed! Please check report view.
<Exception> ShapeBinder.cpp(489): Missing support object
Recompute failed! Please check report view.
<Exception> ShapeBinder.cpp(489): Missing support object
Recompute failed! Please check report view.
<Exception> ShapeBinder.cpp(489): Missing support object
Recompute failed! Please check report view.
<Exception> ShapeBinder.cpp(489): Missing support object
Recompute failed! Please check report view.
<Exception> ShapeBinder.cpp(489): Missing support object
Recompute failed! Please check report view.
<Exception> ShapeBinder.cpp(489): Missing support object
Recompute failed! Please check report view.
Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f895b514210]
#1  /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so(+0x2c6f35) [0x7f894d4e2f35]
#2  0x7f88aff63b12 in PartGui::SoBrepFaceSet::renderFaces(SoCoordinateElement const*, int const*, int, int const*, int, int, SbVec3f const*, int const*, SoMaterialBundle*, int const*, SoTextureCoordinateBundle&, int const*, int, int, int) from /home/arne/src/LinkStage3/build/Mod/Part/PartGui.so+0xec2
#3  0x7f88aff68e03 in PartGui::SoBrepFaceSet::renderShape(SoGLRenderAction*) from /home/arne/src/LinkStage3/build/Mod/Part/PartGui.so+0x363
#4  0x7f88aff6ace8 in PartGui::SoBrepFaceSet::renderShape(SoGLRenderAction*, std::shared_ptr<Gui::SoFCSelectionContextEx>, std::shared_ptr<Gui::SoFCSelectionContextEx>, bool, bool) from /home/arne/src/LinkStage3/build/Mod/Part/PartGui.so+0x3f8
#5  0x7f88aff6cade in PartGui::SoBrepFaceSet::glRender(SoGLRenderAction*, bool) from /home/arne/src/LinkStage3/build/Mod/Part/PartGui.so+0x17ee
#6  0x7f895b10ad02 in SoSeparator::GLRenderBelowPath(SoGLRenderAction*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x3d2
#7  0x7f895b10ad02 in SoSeparator::GLRenderBelowPath(SoGLRenderAction*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x3d2
#8  0x7f895af0f277 in SoAction::traverse(SoNode*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x67
#9  0x7f895b0a64d8 in SoChildList::traverse(SoAction*, int, int) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x168
#10  0x7f895e16ae1f in Gui::SoFCSwitch::doAction(SoAction*) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0x75f
#11  0x7f895b10a1ce in SoSeparator::GLRenderInPath(SoGLRenderAction*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x4be
#12  0x7f895e169b6e in Gui::SoFCSelectionRoot::_renderPrivate(SoGLRenderAction*, bool, bool&) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0x8ae
#13  0x7f895e16a0b4 in Gui::SoFCSelectionRoot::renderPrivate(SoGLRenderAction*, bool) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0xd4
#14  0x7f895b0f144a in SoGroup::GLRender(SoGLRenderAction*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0xca
#15  0x7f895af0f277 in SoAction::traverse(SoNode*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x67
#16  0x7f895b0a63f7 in SoChildList::traverse(SoAction*, int, int) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x87
#17  0x7f895e16abd5 in Gui::SoFCSwitch::doAction(SoAction*) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0x515
#18  0x7f895b10a1ce in SoSeparator::GLRenderInPath(SoGLRenderAction*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x4be
#19  0x7f895e169b6e in Gui::SoFCSelectionRoot::_renderPrivate(SoGLRenderAction*, bool, bool&) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0x8ae
#20  0x7f895e16a0b4 in Gui::SoFCSelectionRoot::renderPrivate(SoGLRenderAction*, bool) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0xd4
#21  0x7f895b10a1ce in SoSeparator::GLRenderInPath(SoGLRenderAction*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x4be
#22  0x7f895e169b6e in Gui::SoFCSelectionRoot::_renderPrivate(SoGLRenderAction*, bool, bool&) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0x8ae
#23  0x7f895e16a0b4 in Gui::SoFCSelectionRoot::renderPrivate(SoGLRenderAction*, bool) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0xd4
#24  0x7f895af0f277 in SoAction::traverse(SoNode*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x67
#25  0x7f895b0a63f7 in SoChildList::traverse(SoAction*, int, int) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x87
#26  0x7f895e16abd5 in Gui::SoFCSwitch::doAction(SoAction*) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0x515
#27  0x7f895b10a1ce in SoSeparator::GLRenderInPath(SoGLRenderAction*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x4be
#28  0x7f895e169b6e in Gui::SoFCSelectionRoot::_renderPrivate(SoGLRenderAction*, bool, bool&) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0x8ae
#29  0x7f895e16a0b4 in Gui::SoFCSelectionRoot::renderPrivate(SoGLRenderAction*, bool) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0xd4
#30  0x7f895b10a1ce in SoSeparator::GLRenderInPath(SoGLRenderAction*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x4be
#31  0x7f895e166429 in Gui::SoFCPathAnnotation::GLRenderBelowPath(SoGLRenderAction*) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0x489
#32  0x7f895b10a1ce in SoSeparator::GLRenderInPath(SoGLRenderAction*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x4be
#33  0x7f895e16996c in Gui::SoFCSelectionRoot::_renderPrivate(SoGLRenderAction*, bool, bool&) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0x6ac
#34  0x7f895e16a0b4 in Gui::SoFCSelectionRoot::renderPrivate(SoGLRenderAction*, bool) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0xd4
#35  0x7f895af0f277 in SoAction::traverse(SoNode*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x67
#36  0x7f895b0a63f7 in SoChildList::traverse(SoAction*, int, int) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x87
#37  0x7f895e16abd5 in Gui::SoFCSwitch::doAction(SoAction*) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0x515
#38  0x7f895b10a1ce in SoSeparator::GLRenderInPath(SoGLRenderAction*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x4be
#39  0x7f895b10a1ce in SoSeparator::GLRenderInPath(SoGLRenderAction*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x4be
#40  0x7f895af0f277 in SoAction::traverse(SoNode*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x67
#41  0x7f895af168a5 in SoGLRenderAction::beginTraversal(SoNode*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x185
#42  0x7f895af0ff11 in SoAction::apply(SoPathList const&, int) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x571
#43  0x7f895e174806 in Gui::SoBoxSelectionRenderAction::apply(SoPathList const&, int) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0x116
#44  0x7f895af1611d in SoGLRenderActionP::renderSingle(SoNode*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x26d
#45  0x7f895af165c3 in SoGLRenderActionP::render(SoNode*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x113
#46  0x7f895af167c3 in SoGLRenderAction::beginTraversal(SoNode*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0xa3
#47  0x7f895af0f71a in SoAction::apply(SoNode*) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x28a
#48  0x7f895e177ded in Gui::SoBoxSelectionRenderAction::apply(SoNode*) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0x2d
#49  0x7f895b1cf3ed in SoRenderManager::renderScene(SoGLRenderAction*, SoNode*, unsigned int) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x4d
#50  0x7f895b1d0573 in SoRenderManager::actuallyRender(SoGLRenderAction*, int, int, int) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x73
#51  0x7f895b1d0712 in SoRenderManager::renderSingle(SoGLRenderAction*, int, int, int) from /lib/x86_64-linux-gnu/libCoin.so.80c+0xc2
#52  0x7f895b1d0d51 in SoRenderManager::render(SoGLRenderAction*, int, int, int) from /lib/x86_64-linux-gnu/libCoin.so.80c+0xb1
#53  0x7f895b1cebff in SoRenderManager::render(int, int) from /lib/x86_64-linux-gnu/libCoin.so.80c+0x8f
#54  0x7f895e23a8a8 in Gui::View3DInventorViewer::renderScene() from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0x248
#55  0x7f895e1f76fd in SIM::Coin3D::Quarter::QuarterWidget::paintEvent(QPaintEvent*) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0x30d
#56  0x7f895e1ff1f6 in SIM::Coin3D::Quarter::SoQTQuarterAdaptor::paintEvent(QPaintEvent*) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0x46
#57  0x7f895c59f2b6 in QWidget::event(QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x286
#58  0x7f895c64cd52 in QFrame::event(QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x22
#59  0x7f895c8b7421 in QGraphicsView::viewportEvent(QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x161
#60  0x7f895e1f77de in SIM::Coin3D::Quarter::QuarterWidget::viewportEvent(QEvent*) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0x9e
#61  0x7f895bb4264b in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x9b
#62  0x7f895c55ca55 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x75
#63  0x7f895c5660f0 in QApplication::notify(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x330
#64  0x7f895dec6918 in Gui::GUIApplication::notify(QObject*, QEvent*) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0x88
#65  0x7f895bb4293a in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x18a
#66  0x7f895c597f4a in QWidgetPrivate::sendPaintEvent(QRegion const&) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x3a
#67  /lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x17c732) [0x7f895c56e732]
#68  /lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x17cdc1) [0x7f895c56edc1]
#69  0x7f895c587385 in QWidgetPrivate::syncBackingStore() from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0xa5
#70  0x7f895c59fcac in QWidget::event(QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0xc7c
#71  0x7f895c6b4148 in QMainWindow::event(QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x68
#72  0x7f895e3053eb in Gui::MainWindow::event(QEvent*) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0x7b
#73  0x7f895c55ca66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x86
#74  0x7f895c5660f0 in QApplication::notify(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x330
#75  0x7f895dec6918 in Gui::GUIApplication::notify(QObject*, QEvent*) from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0x88
#76  0x7f895bb4293a in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x18a
#77  0x7f895bb455b8 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x148
#78  /lib/x86_64-linux-gnu/libQt5Core.so.5(+0x2def67) [0x7f895bb9af67]
#79  /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x27d) [0x7f8959802fbd]
#80  /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x52240) [0x7f8959803240]
#81  /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x7f89598032e3]
#82  0x7f895bb9a565 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x65
#83  0x7f895bb414db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x12b
#84  0x7f895bb49246 in QCoreApplication::exec() from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x96
#85  0x7f895de20b0c in Gui::Application::runApplication() from /home/arne/src/LinkStage3/build/lib/libFreeCADGui.so+0x166c
#86  ./bin/FreeCAD(+0x4c8e) [0x55d6d08d5c8e]
#87  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f895b4f50b3]
#88  ./bin/FreeCAD(+0x501e) [0x55d6d08d601e]
```

**Comment by dulouie** [comment]
But it's strange sometimes it happens and sometime not. Sorry maybe i had forgotten to recompile with the up-to-date state.

**Comment by luzpaz** [comment]
@dulouie any updates on this?
