### ISSUE TITLE
appimage is broken on latest PopOS/Ubuntu,  <asm3.main> init_gui.py(14): no solver backend found

### ISSUE THREAD

**Issue by antonkulaga** [realthunder/FreeCAD#694]
![image](https://user-images.githubusercontent.com/842436/213938601-1f673838-307e-47b3-9bf0-a22426f752e6.png)
I see only black screen and 22:23:47  0.874944 <asm3.main> init_gui.py(14): no solver backend found

**Comment by realthunder** [comment]
Can you please try [this](https://drive.google.com/file/d/14SSynSLbqomZteZ4FDFqH6bXmr46h4cN/view?usp=share_link).

**Comment by apper002** [comment]
~/Desktop$ ./FreeCad-20230131 
/tmp/.mount_FreeCaKje4JN
FreeCAD 0.20, Libs: 2023.131R26244 +5365 (Git)
flag
flag2
1.954259 <asm3.main> init_gui.py(14): no solver backend found

Linux kloksup 5.15.0-57-generic #63-Ubuntu SMP Thu Nov 24 13:43:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

**Comment by antonkulaga** [comment]
I managed to make it work even with the previous backend by installing the solver on my system instead of expecting it to be in the app image. However, the black screen on the first page was a disorienting

**Comment by apper002** [comment]
Should all be in the App image.

**Comment by apper002** [comment]
./FreeCAD-asm3-Daily-Conda-Py3.10-20230122-glibc2.12-x86_64-RealT.AppImage
/tmp/.mount_FreeCAKguSZa
FreeCAD 0.20, Libs: 2023.122R26244 +5349 (Git)
flag
flag2
1.936934 <asm3.main> init_gui.py(14): no solver backend found

**Comment by apper002** [comment]
Installing Add-On

copying macro: BCFPlugin.FCMacro
Traceback (most recent call last):
  File "/tmp/.mount_FreeCAKguSZa/usr/Mod/AddonManager/addonmanager_utilities.py", line 126, in urlopen
    u = urllib2.urlopen(req, timeout=timeout)
  File "/tmp/.mount_FreeCAKguSZa/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/tmp/.mount_FreeCAKguSZa/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/tmp/.mount_FreeCAKguSZa/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/tmp/.mount_FreeCAKguSZa/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/tmp/.mount_FreeCAKguSZa/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/tmp/.mount_FreeCAKguSZa/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 504: Gateway Timeout
Failed to get url https://camo.githubusercontent.com/508bd4a38bbee8e08c57f3b0af5e2604159311d31225e8a4d2f688041053ca4b/68747470733a2f2f696d672e736869656c64732e696f2f6c67746d2f67726164652f707974686f6e2f672f4475616c53504879736963732f44657369676e53504879736963732e7376673f6c6f676f3d6c67746d266c6f676f57696474683d3138
AddonManager: Debug: Error retrieving image from https://camo.githubusercontent.com/508bd4a38bbee8e08c57f3b0af5e2604159311d31225e8a4d2f688041053ca4b/68747470733a2f2f696d672e736869656c64732e696f2f6c67746d2f67726164652f707974686f6e2f672f4475616c53504879736963732f44657369676e53504879736963732e7376673f6c6f676f3d6c67746d266c6f676f57696474683d3138

**Comment by apper002** [comment]
Agreed: Ubuntu is a mess nowadays.....

**Comment by luzpaz** [comment]
What's left to do here ?

**Comment by vido89** [comment]
Im using Mint and Im also getting an error `1.473896 <asm3.main> init_gui.py(14): no solver backend found`

**Comment by vido89** [comment]
@realthunder I tried that link an same error
