### ISSUE TITLE
the program drops at attempt to select a group of elements in the sketch.

### ISSUE THREAD

**Issue by tiket18** [realthunder/FreeCAD#70]
Let us create a new file, a thumbnail in it, and a rectangle in it. Now, by clicking the left mouse button, we will try to select elements moving from the upper left to the lower right (or vice versa) = the program drops.

This phenomenon appeared after merging with the apstream

The last appimadge is sick -
OS: Arch Linux (GNOME/gnome-xorg)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2020.11.26.23076 +2838 (Git) AppImage
Build type: Release
Branch: LinkStage3
Hash: 34f56bf31f0cb82d0cff586b2c2fddf206a68d8a
Python version: 3.8.6
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.4.0
Locale: Russian/Russia (ru_RU)

Version 2836 does not suffer from this.

[abort.FCStd.zip](https://github.com/realthunder/FreeCAD/files/5603057/abort.FCStd.zip)

` freecad
FreeCAD 0.19, Libs: 0.19R25914 (Git)
© Juergen Riegel, Werner Mayer, Yorik van Havre and others 2001-2020
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.
FreeCAD wouldn't be possible without FreeCAD community.
  #####                 ####  ###   ####  
  #                    #      # #   #   # 
  #     ##  #### ####  #     #   #  #   # 
  ####  # # #  # #  #  #     #####  #   # 
  #     #   #### ####  #    #     # #   # 
  #     #   #    #     #    #     # #   #  ##  ##  ##
  #     #   #### ####   ### #     # ####   ##  ##  ##

Loading Assembly4 WorkBench

(freecad:1014694): Gtk-WARNING **: 15:34:54.044: Theme parsing error: gtk.css:4:108: Failed to import: Произошла ошибка открытия файла .local/share/gnome-shell/extensions/no-title-bar@jonaspoehler.de/stylesheet.css: Нет такого файла или каталога

(freecad:1014694): Gtk-WARNING **: 15:34:54.044: Theme parsing error: gtk.css:5:114: Failed to import: Произошла ошибка открытия файла .local/share/gnome-shell/extensions/no-title-bar@jonaspoehler.de/stylesheet-tiled.css: Нет такого файла или каталога
<Command> Command.cpp(1901): duplicate command Std_TreePreSelection
<Command> Command.cpp(1901): duplicate command Std_TreePreSelection
1.224623 <asm3.main> init_gui.py(14): no solver backend found
connect failed: Нет такого файла или каталога
Program received signal SIGSEGV, Segmentation fault.
#0  /usr/lib/libc.so.6(+0x3d6a0) [0x7f8fb39c16a0]
#1  0x7f8fb36d0c0f in SoMarkerSet::getMarker(int, SbVec2s&, unsigned char const*&, int&) from /usr/lib/libCoin.so.80+0x1f
#2  0x7f8fb36c15b8 in SoIndexedMarkerSet::GLRender(SoGLRenderAction*) from /usr/lib/libCoin.so.80+0x3c8
#3  0x7f8fb35850e3 in SoSeparator::GLRenderBelowPath(SoGLRenderAction*) from /usr/lib/libCoin.so.80+0x403
#4  0x7f8fb335e9d7 in SoAction::traverse(SoNode*) from /usr/lib/libCoin.so.80+0x67
#5  0x7f8fb351b4ab in SoChildList::traverse(SoAction*, int, int) from /usr/lib/libCoin.so.80+0x16b
#6  0x7f8fb35891e1 in SoSwitch::doAction(SoAction*) from /usr/lib/libCoin.so.80+0x2b1
#7  0x7f8fb35850e3 in SoSeparator::GLRenderBelowPath(SoGLRenderAction*) from /usr/lib/libCoin.so.80+0x403
#8  0x7f8fb3583fe1 in SoSeparator::GLRenderInPath(SoGLRenderAction*) from /usr/lib/libCoin.so.80+0x51
#9  0x7f8fb3554af7 in SoAnnotation::GLRenderInPath(SoGLRenderAction*) from /usr/lib/libCoin.so.80+0x97
#10  0x7f8fb35844d5 in SoSeparator::GLRenderInPath(SoGLRenderAction*) from /usr/lib/libCoin.so.80+0x545
#11  0x7f8fb35844d5 in SoSeparator::GLRenderInPath(SoGLRenderAction*) from /usr/lib/libCoin.so.80+0x545
#12  0x7f8fb335e9d7 in SoAction::traverse(SoNode*) from /usr/lib/libCoin.so.80+0x67
#13  0x7f8fb335f352 in SoAction::apply(SoPathList const&, int) from /usr/lib/libCoin.so.80+0x5b2
#14  0x7f8fb3365ab7 in SoGLRenderActionP::renderSingle(SoNode*) from /usr/lib/libCoin.so.80+0x277
#15  0x7f8fb3365fbe in SoGLRenderActionP::render(SoNode*) from /usr/lib/libCoin.so.80+0x11e
#16  0x7f8fb335f6ba in SoAction::apply(SoNode*) from /usr/lib/libCoin.so.80+0x2ea
#17  0x7f8fb64c5b6a in Gui::SoBoxSelectionRenderAction::apply(SoNode*) from /usr/lib/freecad/lib/libFreeCADGui.so+0x2a
#18  0x7f8fb3658962 in SoRenderManager::actuallyRender(SoGLRenderAction*, int, int, int) from /usr/lib/libCoin.so.80+0xa2
#19  0x7f8fb3658b17 in SoRenderManager::renderSingle(SoGLRenderAction*, int, int, int) from /usr/lib/libCoin.so.80+0xc7
#20  0x7f8fb365914c in SoRenderManager::render(SoGLRenderAction*, int, int, int) from /usr/lib/libCoin.so.80+0x9c
#21  0x7f8fb65934bc in Gui::View3DInventorViewer::renderScene() from /usr/lib/freecad/lib/libFreeCADGui.so+0x2cc
#22  0x7f8fb6549ffd in SIM::Coin3D::Quarter::QuarterWidget::paintEvent(QPaintEvent*) from /usr/lib/freecad/lib/libFreeCADGui.so+0x33d
#23  0x7f8fb6554545 in SIM::Coin3D::Quarter::SoQTQuarterAdaptor::paintEvent(QPaintEvent*) from /usr/lib/freecad/lib/libFreeCADGui.so+0x45
#24  0x7f8fb4b04b0e in QWidget::event(QEvent*) from /usr/lib/libQt5Widgets.so.5+0x1ce
#25  0x7f8fb4bb016f in QFrame::event(QEvent*) from /usr/lib/libQt5Widgets.so.5+0x1f
#26  0x7f8fb3ff97e3 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) from /usr/lib/libQt5Core.so.5+0x93
#27  0x7f8fb4ac3741 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /usr/lib/libQt5Widgets.so.5+0x71
#28  0x7f8fb61fac99 in Gui::GUIApplication::notify(QObject*, QEvent*) from /usr/lib/freecad/lib/libFreeCADGui.so+0x89
#29  0x7f8fb3ff9a7a in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /usr/lib/libQt5Core.so.5+0x12a
#30  0x7f8fb4afc8e8 in QWidgetPrivate::sendPaintEvent(QRegion const&) from /usr/lib/libQt5Widgets.so.5+0x38
#31  /usr/lib/libQt5Widgets.so.5(+0x16b666) [0x7f8fb4ad4666]
#32  0x7f8fb4b0525b in QWidget::event(QEvent*) from /usr/lib/libQt5Widgets.so.5+0x91b
#33  0x7f8fb4ac3752 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /usr/lib/libQt5Widgets.so.5+0x82
#34  0x7f8fb61fac99 in Gui::GUIApplication::notify(QObject*, QEvent*) from /usr/lib/freecad/lib/libFreeCADGui.so+0x89
#35  0x7f8fb3ff9a7a in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /usr/lib/libQt5Core.so.5+0x12a
#36  0x7f8fb3ffc573 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) from /usr/lib/libQt5Core.so.5+0x173
#37  /usr/lib/libQt5Core.so.5(+0x30f0a4) [0x7f8fb40530a4]
#38  /usr/lib/libglib-2.0.so.0(g_main_context_dispatch+0x184) [0x7f8fb1d1e914]
#39  /usr/lib/libglib-2.0.so.0(+0xa67d1) [0x7f8fb1d727d1]
#40  /usr/lib/libglib-2.0.so.0(g_main_context_iteration+0x31) [0x7f8fb1d1d121]
#41  0x7f8fb40526e1 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /usr/lib/libQt5Core.so.5+0x61
#42  0x7f8fb3ff83fc in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /usr/lib/libQt5Core.so.5+0x12c
#43  0x7f8fb4000894 in QCoreApplication::exec() from /usr/lib/libQt5Core.so.5+0x94
#44  0x7f8fb614ec4c in Gui::Application::runApplication() from /usr/lib/freecad/lib/libFreeCADGui.so+0x181c
#45  freecad(+0x45e0) [0x56456f0e85e0]
#46  /usr/lib/libc.so.6(__libc_start_main+0xf2) [0x7f8fb39ac152]
#47  freecad(+0x48ee) [0x56456f0e88ee]

`

**Comment by tiket18** [comment]
problem no solved

OS: Arch Linux (GNOME/gnome-xorg)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.25921 (Git)
Build type: Release
Branch: makepkg
Hash: f4fbc8c51dbe826c42db60c9c49876851f41362b
Python version: 3.8.6
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: Russian/Russia (ru_RU)

**Comment by tiket18** [comment]
problem  solved

OS: Arch Linux (GNOME/gnome-xorg)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.25923 (Git)
Build type: Release
Branch: makepkg
Hash: 550a1f4894e08fa6dae9bcd12cf29b02346655fa
Python version: 3.8.6
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: Russian/Russia (ru_RU)
