### ISSUE TITLE
Addon Manager freeze

### ISSUE THREAD

**Issue by pippel** [realthunder/FreeCAD#822]
macros cannot be installed.
Addon Manager freezes.

**Comment by pippel** [comment]
Linux Debian 11,  FreeCAD-Link-Tip-Linux-x86_64-py3.11-20230516.AppImage

**Comment by katodo** [comment]
same problem on my  Kubuntu 22.04 and FreeCAD-Link-Tip-Linux-x86_64-py3.11-20230516.appimage

**Comment by pippel** [comment]
Debian 11 , FreeCAD-Link-Tip-Linux-x86_64-py3.11-20230521.AppImage

sorry, no change.
Macro installation still does not work.
![freecad2](https://github.com/realthunder/FreeCAD/assets/17956008/fcf9f381-8617-43c9-806e-0209c4dcb838)

**Comment by pippel** [comment]
i had deleted all existing directories after downloading the new version FreeCAD-Link-Tip-Linux-x86_64-py3.11-20230521.AppImage.
Unfortunately unsuccessfully.

Question,
is it correct that the freecad appimage in the cache directory
now creates two folders
FreeCAD and FreeCAD Link Branch ?
Under .cache/FreeCAD are still created Cache/Addonmanager and Freecad_4646.lock.

**Comment by realthunder** [comment]
Can you please translate the error message in your screen shot?

**Comment by pippel** [comment]
Since the closing of the window does not work via the "close" button (no reaction) this message appears about closing with the X button at the top of the window frame

Warning - window management
You have tried to close the 'Addon Manager' window of the 'freecad link branch' application (process identifier: 4646).
However, the application does not respond. Do you want to close this application?
Warning: If you close the application, all windows belonging to the application will be shot and unsaved data will be lost.

yes no
![freecad](https://github.com/realthunder/FreeCAD/assets/17956008/c6c0f142-8939-4479-83db-0ac7564786db)

**Comment by 3nt3** [comment]
These are the errors outputted to stderr when I open the addon manager

```
Traceback (most recent call last):
  File "/tmp/.mount_FreeCAMrRGN7/usr/Mod/AddonManager/addonmanager_git.py", line 364, in _synchronous_call_git
    proc = utils.run_interruptable_subprocess(final_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_FreeCAMrRGN7/usr/Mod/AddonManager/addonmanager_utilities.py", line 452, in run_interruptable_subprocess
    raise subprocess.CalledProcessError(return_code, args, stdout, stderr)
subprocess.CalledProcessError: Command '['/tmp/.mount_FreeCAMrRGN7/usr/bin/git', 'clone', '--recurse-submodules', 'https://github.com/FreeCAD/FreeCAD-macros.git', '/home/ente/.cache/FreeCAD/Cache/AddonManager/Macros']' returned non-zero exit status 128.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/.mount_FreeCAMrRGN7/usr/Mod/AddonManager/addonmanager_workers_startup.py", line 324, in _update_local_git_repo
    self.git_manager.clone(
  File "/tmp/.mount_FreeCAMrRGN7/usr/Mod/AddonManager/addonmanager_git.py", line 83, in clone
    self._synchronous_call_git(final_args)
  File "/tmp/.mount_FreeCAMrRGN7/usr/Mod/AddonManager/addonmanager_git.py", line 366, in _synchronous_call_git
    raise GitFailed(
addonmanager_git.GitFailed: Git returned a non-zero exit status: 128
Called with: /tmp/.mount_FreeCAMrRGN7/usr/bin/git clone --recurse-submodules https://github.com/FreeCAD/FreeCAD-macros.git /home/ente/.cache/FreeCAD/Cache/AddonManager/Macros

Returned stderr:
Cloning into '/home/ente/.cache/FreeCAD/Cache/AddonManager/Macros'...
warning: templates not found in /home/runner/work/FreeCAD/FreeCAD/build/AppDir/usr/././././././././././././././././././././././././../share/git-core/templates
git: 'remote-https' is not a git command. See 'git --help'.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/.mount_FreeCAMrRGN7/usr/Mod/AddonManager/addonmanager_workers_startup.py", line 87, in run
    self._retrieve_macros_from_git()
  File "/tmp/.mount_FreeCAMrRGN7/usr/Mod/AddonManager/addonmanager_workers_startup.py", line 273, in _retrieve_macros_from_git
    update_succeeded = self._update_local_git_repo()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_FreeCAMrRGN7/usr/Mod/AddonManager/addonmanager_workers_startup.py", line 342, in _update_local_git_repo
    os.chdir(
FileNotFoundError: [Errno 2] No such file or directory: '/home/ente/.cache/FreeCAD/Cache/AddonManager/Macros/..'
```

**Comment by totoff974** [comment]
I had the same problem in order to avoid the freeze, I added in "Edit/Preferences/Addon Manager" the path manually to the Python and Git executable.
![Capture_Freecad](https://github.com/realthunder/FreeCAD/assets/24492813/4805bff7-a5e8-4c0d-9a24-29b783d3d5b5)

**Comment by pippel** [comment]
@totoff974 
you using the Linux app image? 
FreeCAD-Link-Tip-Linux-x86_64-py3.11-20230521.AppImage

**Comment by pippel** [comment]
Just tried it, works great with the appimage. thanks a lot

**Comment by totoff974** [comment]
> @totoff974 you using the Linux app image? FreeCAD-Link-Tip-Linux-x86_64-py3.11-20230521.AppImage

yep! 
[code]
OS: Ubuntu 22.04.2 LTS
Word size of FreeCAD: 64-bit
Version: 2023.521.0.14555 (Git shallow) AppImage
[/code]

**Comment by paulcobbaut** [comment]
Same issue on Debian 11 with FreeCAD-Link-Tip-Linux-x86_64-py3.11-20230521
@totoff974 solution works, thanks!

**Comment by rewthing** [comment]
I'm having the same problem on Windows with release 2024.123.0:  Anything that requires git to use HTTPS fails, because the bundled git is being built _without_ TLS support, so git-remote-https.exe does not exist.

While Linux/MacOS systems often have git installed elsewhere (e.g. outside the AppImage, for Linux), many Windows systems lack an alternative git installation, so providing a path to an external git binary is not a good workaround for most Windows users.

A good long-term fix might be to build the bundled git with TLS support, per: https://stackoverflow.com/questions/51366101/git-remote-https-is-not-a-git-command

**Comment by duke2421** [comment]
@rewthing Did you start FreeCad directly with the FreeCADLink.exe inside bin/ or with the RunFreeCAD.bat. If you use the bat file, everything should work just fine.
