### ISSUE TITLE
While opening Addon Manager: git: 'remote-https' is not a git command

### ISSUE THREAD

**Issue by psommerfeld** [realthunder/FreeCAD#831]
Can't add any add-ons. Error when opening Addon Manager.
I was able to install the add-on (BIM, in my case) by doing it with the latest main-branch build and then it was accessible again in the Link Daily branch.

07:15:18  An error occurred updating macros from GitHub, trying clean checkout...:
Git returned a non-zero exit status: 128
Called with: /Applications/FreeCAD link 2023.05.21.app/Contents/Resources/bin/git clone --recurse-submodules https://github.com/FreeCAD/FreeCAD-macros.git /Users/psommerfeld/Library/Caches/FreeCAD/Cache/AddonManager/Macros

Returned stderr:
Cloning into '/Users/psommerfeld/Library/Caches/FreeCAD/Cache/AddonManager/Macros'...
warning: templates not found in /Users/runner/work/FreeCAD/FreeCAD/build/FreeCAD.app/Contents/Resources/share/git-core/templates
git: 'remote-https' is not a git command. See 'git --help'.

07:15:18  /Users/psommerfeld/Library/Caches/FreeCAD/Cache/AddonManager/Macros
07:15:18  Attempting to do a clean checkout...
07:15:18  Traceback (most recent call last):
07:15:18    File "/Applications/FreeCAD link 2023.05.21.app/Contents/Resources/Mod/AddonManager/addonmanager_git.py", line 364, in _synchronous_call_git
07:15:18      proc = utils.run_interruptable_subprocess(final_args)
07:15:18             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
07:15:18    File "/Applications/FreeCAD link 2023.05.21.app/Contents/Resources/Mod/AddonManager/addonmanager_utilities.py", line 452, in run_interruptable_subprocess
07:15:18      raise subprocess.CalledProcessError(return_code, args, stdout, stderr)
07:15:18  subprocess.CalledProcessError: Command '['/Applications/FreeCAD link 2023.05.21.app/Contents/Resources/bin/git', 'clone', '--recurse-submodules', 'https://github.com/FreeCAD/FreeCAD-macros.git', '/Users/psommerfeld/Library/Caches/FreeCAD/Cache/AddonManager/Macros']' returned non-zero exit status 128.
07:15:18  
07:15:18  During handling of the above exception, another exception occurred:
07:15:18  
07:15:18  Traceback (most recent call last):
07:15:18    File "/Applications/FreeCAD link 2023.05.21.app/Contents/Resources/Mod/AddonManager/addonmanager_workers_startup.py", line 324, in _update_local_git_repo
07:15:18      self.git_manager.clone(
07:15:18    File "/Applications/FreeCAD link 2023.05.21.app/Contents/Resources/Mod/AddonManager/addonmanager_git.py", line 83, in clone
07:15:18      self._synchronous_call_git(final_args)
07:15:18    File "/Applications/FreeCAD link 2023.05.21.app/Contents/Resources/Mod/AddonManager/addonmanager_git.py", line 366, in _synchronous_call_git
07:15:18      raise GitFailed(
07:15:18  addonmanager_git.GitFailed: Git returned a non-zero exit status: 128
Called with: /Applications/FreeCAD link 2023.05.21.app/Contents/Resources/bin/git clone --recurse-submodules https://github.com/FreeCAD/FreeCAD-macros.git /Users/psommerfeld/Library/Caches/FreeCAD/Cache/AddonManager/Macros

Returned stderr:
Cloning into '/Users/psommerfeld/Library/Caches/FreeCAD/Cache/AddonManager/Macros'...
warning: templates not found in /Users/runner/work/FreeCAD/FreeCAD/build/FreeCAD.app/Contents/Resources/share/git-core/templates
git: 'remote-https' is not a git command. See 'git --help'.
07:15:18  
07:15:18  
07:15:18  During handling of the above exception, another exception occurred:
07:15:18  
07:15:18  Traceback (most recent call last):
07:15:18    File "/Applications/FreeCAD link 2023.05.21.app/Contents/Resources/Mod/AddonManager/addonmanager_workers_startup.py", line 87, in run
07:15:18      self._retrieve_macros_from_git()
07:15:18    File "/Applications/FreeCAD link 2023.05.21.app/Contents/Resources/Mod/AddonManager/addonmanager_workers_startup.py", line 273, in _retrieve_macros_from_git
07:15:18      update_succeeded = self._update_local_git_repo()
07:15:18                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
07:15:18    File "/Applications/FreeCAD link 2023.05.21.app/Contents/Resources/Mod/AddonManager/addonmanager_workers_startup.py", line 342, in _update_local_git_repo
07:15:18      os.chdir(
07:15:18  FileNotFoundError: [Errno 2] No such file or directory: '/Users/psommerfeld/Library/Caches/FreeCAD/Cache/AddonManager/Macros/..'

[code]
OS: macOS 13.0
Word size of FreeCAD: 64-bit
Version: 2023.521.0.14555 (Git shallow)
Build type: Release
Branch: HEAD
Hash: f428979aa87456d1ce57e2ea78ee9d70dc7595e4
Python 3.11.3, Qt 5.15.8, Coin 4.0.1, Vtk 9.2.5, OCC 7.7.1
Locale: C/Default (C)
Installed mods: 
  * fasteners.backup1686222008.1392 0.3.50 (Disabled)
  * ProDarkThemePreferencePack 1.0.0
[/code]

**Comment by AlexDaniel** [comment]
Seems to be a dup of #822, see this for the solution: https://github.com/realthunder/FreeCAD/issues/822#issuecomment-1576111340
