### ISSUE TITLE
Draft - Arc by 3 points causes crash

### ISSUE THREAD

**Issue by Neubo** [realthunder/FreeCAD#849]
Hello,

just found out a new issue.
When trying to make an Arc by 3 points, at the first point selected, command crash:

`11:44:02  GuiCommand: Arc by 3 points
11:44:05  Traceback (most recent call last):
  File "C:\_Data\Freecad\FreeCAD-Link-Tip-Win-x86_64-py3.11-20230521\Mod\asm3\.\freecad\asm3\gui.py", line 143, in removePreselection
    self.setElementVisible(docname,objname,subname,False,True)
  File "C:\_Data\Freecad\FreeCAD-Link-Tip-Win-x86_64-py3.11-20230521\Mod\asm3\.\freecad\asm3\gui.py", line 74, in setElementVisible
    if FreeCAD.isRestoring():
       ^^^^^^^^^^^^^^^^^^^^^
<class 'SystemError'>: <built-in function isRestoring> returned a result with an exception set`

```
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 2023.524.0.14555 (Git shallow)
Build type: Release
Branch: HEAD
Hash: f428979aa87456d1ce57e2ea78ee9d70dc7595e4
Python 3.11.3, Qt 5.15.6, Coin 4.0.1, Vtk 9.2.5, OCC 7.7.1
Locale: French/France (fr_FR)
Installed mods: 
  * DVPScaled.brep
  * Manipulator 1.5.0
  * parts_library
  * QuickMeasure 2022.10.28
```

**Comment by Neubo** [comment]
Hello,

just tested with last Tip version, and looks ok now !
issue could be closed.


```
OS: Windows 11 build 22621
Word size of FreeCAD: 64-bit
Version: 2023.731.0.14555 (Git shallow)
Build type: Release
Branch: HEAD
Hash: 311c0066f7d2e5599a76337706627b6c27f6dc2b
Python 3.11.4, Qt 5.15.6, Coin 4.0.1, Vtk 9.2.5, OCC 7.7.2
Locale: French/France (fr_FR)
Installed mods: 
  * DVPScaled.brep
  * Manipulator 1.5.0
  * parts_library
  * QuickMeasure 2022.10.28
```
