### ISSUE TITLE
Segmentation fault with File->Alignment

### ISSUE THREAD

**Issue by mousethief** [realthunder/FreeCAD#906]
I am trying to align two objects by face onto the same plane. Search queries such as 'freecad align two objects to the same plane' all return basically the same process: Select face on first object, select face on second object, File->Alignment, then use the options that appear. Instead, upon selecting the menu item, the program crashes.

As I'm running this fork from the appimage I figured I would start here. This happens consistently with the 20230811 and 20231102 Linux appimage builds. I'm running on Debian 11.7

**Comment by mousethief** [comment]
The actual segfault is
```
Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libc.so.6(+0x38d60) [0x7f76a0864d60]
#1  0x7f76a239b670 in Gui::Document::getViewProvider(App::DocumentObject const*) const from /tmp/.mount_FreeCAMy4Su8/usr/bin/../lib/libFreeCADGui.so+0
#2  0x7f76a2437579 in Gui::AlignmentGroup::addView(App::DocumentObject*) from /tmp/.mount_FreeCAMy4Su8/usr/bin/../lib/libFreeCADGui.so+0x49
#3  0x7f76a24a89d4 in StdCmdAlignment::activated(int) from /tmp/.mount_FreeCAMy4Su8/usr/bin/../lib/libFreeCADGui.so+0x274
#4  0x7f76a249b5a7 in Gui::Command::_invoke(int, bool) from /tmp/.mount_FreeCAMy4Su8/usr/bin/../lib/libFreeCADGui.so+0x237
#5  0x7f76a249ba27 in Gui::Command::invoke(int, Gui::Command::TriggerSource) from /tmp/.mount_FreeCAMy4Su8/usr/bin/../lib/libFreeCADGui.so+0x187
#6  /tmp/.mount_FreeCAMy4Su8/usr/bin/../lib/libQt5Core.so.5(+0x1dff9b) [0x7f769ffdff9b]
#7  0x7f76a0b65136 in QAction::triggered(bool) from /tmp/.mount_FreeCAMy4Su8/usr/bin/../lib/libQt5Widgets.so.5+0x32
#8  0x7f76a0b66c20 in QAction::activate(QAction::ActionEvent) from /tmp/.mount_FreeCAMy4Su8/usr/bin/../lib/libQt5Widgets.so.5+0xc6
#9  /tmp/.mount_FreeCAMy4Su8/usr/bin/../lib/libQt5Widgets.so.5(+0x259c3f) [0x7f76a0c59c3f]
#10  /tmp/.mount_FreeCAMy4Su8/usr/bin/../lib/libQt5Widgets.so.5(+0x25eb0e) [0x7f76a0c5eb0e]
#11  0x7f76a0b94202 in QWidget::event(QEvent*) from /tmp/.mount_FreeCAMy4Su8/usr/bin/../lib/libQt5Widgets.so.5+0x134
#12  0x7f76a0b6a087 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_FreeCAMy4Su8/usr/bin/../lib/libQt5Widgets.so.5+0xd9
#13  0x7f76a0b6e36d in QApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAMy4Su8/usr/bin/../lib/libQt5Widgets.so.5+0x663
#14  0x7f76a240ef99 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAMy4Su8/usr/bin/../lib/libFreeCADGui.so+0x99
#15  0x7f769ffc2a18 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_FreeCAMy4Su8/usr/bin/../lib/libQt5Core.so.5+0x8e
#16  0x7f76a0b6d981 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) from /tmp/.mount_FreeCAMy4Su8/usr/bin/../lib/libQt5Widgets.so.5+0x283
#17  /tmp/.mount_FreeCAMy4Su8/usr/bin/../lib/libQt5Widgets.so.5(+0x1a2e02) [0x7f76a0ba2e02]
#18  /tmp/.mount_FreeCAMy4Su8/usr/bin/../lib/libQt5Widgets.so.5(+0x1a4505) [0x7f76a0ba4505]
#19  0x7f76a0b6a087 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_FreeCAMy4Su8/usr/bin/../lib/libQt5Widgets.so.5+0xd9
#20  0x7f76a240ef99 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAMy4Su8/usr/bin/../lib/libFreeCADGui.so+0x99
#21  0x7f769ffc2a18 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_FreeCAMy4Su8/usr/bin/../lib/libQt5Core.so.5+0x8e
#22  0x7f76a050956e in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) from /tmp/.mount_FreeCAMy4Su8/usr/bin/../lib/libQt5Gui.so.5+0x6b6
#23  0x7f76a04f6091 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAMy4Su8/usr/bin/../lib/libQt5Gui.so.5+0x57
#24  /tmp/.mount_FreeCAMy4Su8/usr/plugins/platforms/../../lib/libQt5XcbQpa.so.5(+0x5672c) [0x7f769516672c]
#25  /tmp/.mount_FreeCAMy4Su8/usr/bin/../lib/./libglib-2.0.so.0(g_main_context_dispatch+0x2ad) [0x7f769e31538d]
#26  /tmp/.mount_FreeCAMy4Su8/usr/bin/../lib/./libglib-2.0.so.0(+0x5d649) [0x7f769e315649]
#27  /tmp/.mount_FreeCAMy4Su8/usr/bin/../lib/./libglib-2.0.so.0(g_main_context_iteration+0x2e) [0x7f769e3156de]
#28  0x7f769fff3d50 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAMy4Su8/usr/bin/../lib/libQt5Core.so.5+0x5c
#29  0x7f769ffc05d8 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAMy4Su8/usr/bin/../lib/libQt5Core.so.5+0x180
#30  0x7f769ffc47af in QCoreApplication::exec() from /tmp/.mount_FreeCAMy4Su8/usr/bin/../lib/libQt5Core.so.5+0x107
#31  0x7f76a2370666 in Gui::Application::runApplication() from /tmp/.mount_FreeCAMy4Su8/usr/bin/../lib/libFreeCADGui.so+0x4b6
#32  ./FreeCADLink(+0x87e6) [0x555d4cd367e6]
#33  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xea) [0x7f76a084fd0a]
#34  ./FreeCADLink(+0x8bad) [0x555d4cd36bad]

```
