### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by yahbluez** [realthunder/FreeCAD#937]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: Manjaro Linux (XFCE/xfce)
Word size of FreeCAD: 64-bit
Version: 2024.113.0.14555 (Git shallow) AppImage
Build type: Release
Branch: HEAD
Hash: 4235ee9c92d9822b434ec2bc8da7cee729fd9f3b
Python 3.11.6, Qt 5.15.8, Coin 4.0.1, Vtk 9.2.5, OCC 7.7.2
Locale: English/United States (en_US)
[/code]


./FreeCAD-Link-Stable-Linux-x86_64-py3.11-20240113.AppImage
```

### Subproject(s) affected?

None

### Problem description

FreeCAD 0.21.0, Libs: 2024.113.0R14555 (Git shallow)
1.247801 <asm3.main> init_gui.py(14): no solver backend found
Program received signal SIGSEGV, Segmentation fault.
#0  /usr/lib/libc.so.6(+0x3e710) [0x7f4545e79710]
#1  0x7f453f76c784 in BRep_Tool::CurveOnSurface(TopoDS_Edge const&, opencascade::handle<Geom_Surface> const&, TopLoc_Location const&, double&, double&, bool*) from /tmp/.mount_FreeCAqk7dC1/usr/lib/./libTKBRep.so.7.7+0x164
#2  0x7f453f76c85f in BRep_Tool::CurveOnSurface(TopoDS_Edge const&, TopoDS_Face const&, double&, double&, bool*) from /tmp/.mount_FreeCAqk7dC1/usr/lib/./libTKBRep.so.7.7+0xaf
#3  0x7f453f77a9ec in BRepAdaptor_Curve2d::Initialize(TopoDS_Edge const&, TopoDS_Face const&) from /tmp/.mount_FreeCAqk7dC1/usr/lib/./libTKBRep.so.7.7+0xdc
#4  0x7f453fb33ce0 in ChFi3d_Builder::StartSol(opencascade::handle<ChFiDS_Spine> const&, opencascade::handle<BRepAdaptor_Surface>&, gp_Pnt2d&, opencascade::handle<BRepAdaptor_Curve2d>&, double&, opencascade::handle<ChFiDS_SurfData> const&, bool, int, opencascade::handle<BRepAdaptor_Surface>&, opencascade::handle<BRepAdaptor_Curve2d>&, bool&, bool&, bool&, bool&, opencascade::handle<BRepAdaptor_Surface>&, gp_Pnt2d&, bool, TopoDS_Vertex const&) const from /tmp/.mount_FreeCAqk7dC1/usr/lib/./libTKFillet.so.7.7+0xd50
#5  0x7f453fb39164 in ChFi3d_Builder::PerformSetOfSurfOnElSpine(opencascade::handle<ChFiDS_ElSpine> const&, opencascade::handle<ChFiDS_Stripe>&, opencascade::handle<BRepTopAdaptor_TopolTool>&, opencascade::handle<BRepTopAdaptor_TopolTool>&, bool) from /tmp/.mount_FreeCAqk7dC1/usr/lib/./libTKFillet.so.7.7+0x684
#6  0x7f453fb3b941 in ChFi3d_Builder::PerformSetOfKGen(opencascade::handle<ChFiDS_Stripe>&, bool) from /tmp/.mount_FreeCAqk7dC1/usr/lib/./libTKFillet.so.7.7+0x101
#7  0x7f453fb410ba in ChFi3d_Builder::PerformSetOfSurf(opencascade::handle<ChFiDS_Stripe>&, bool) from /tmp/.mount_FreeCAqk7dC1/usr/lib/./libTKFillet.so.7.7+0x6a
#8  0x7f453fb050bd in ChFi3d_Builder::Compute() from /tmp/.mount_FreeCAqk7dC1/usr/lib/./libTKFillet.so.7.7+0x42d
#9  0x7f453fc937ce in BRepFilletAPI_MakeChamfer::Build(Message_ProgressRange const&) from /tmp/.mount_FreeCAqk7dC1/usr/lib/./libTKFillet.so.7.7+0x2e
#10  0x7f453e03b1ed in BRepBuilderAPI_MakeShape::Shape() from /tmp/.mount_FreeCAqk7dC1/usr/lib/./libTKTopAlgo.so.7.7+0x8d
#11  0x7f4540f70b39 in Part::TopoShape::makEShape(BRepBuilderAPI_MakeShape&, std::vector<Part::TopoShape, std::allocator<Part::TopoShape> > const&, char const*) from /tmp/.mount_FreeCAqk7dC1/usr/lib/Part.so+0x59
#12  0x7f4540f717f3 in Part::TopoShape::makEShape(BRepBuilderAPI_MakeShape&, Part::TopoShape const&, char const*) from /tmp/.mount_FreeCAqk7dC1/usr/lib/Part.so+0x83
#13  0x7f4540f7460c in Part::TopoShape::makEChamfer(Part::TopoShape const&, std::vector<Part::TopoShape, std::allocator<Part::TopoShape> > const&, std::vector<Part::TopoShape::ChamferInfo, std::allocator<Part::TopoShape::ChamferInfo> > const&, char const*) from /tmp/.mount_FreeCAqk7dC1/usr/lib/Part.so+0x40c
#14  0x7f43d2cf42ec in PartDesign::Chamfer::execute() from /tmp/.mount_FreeCAqk7dC1/usr/lib/_PartDesign.so+0x70c
#15  0x7f4547ae4812 in App::DocumentObject::recompute() from /tmp/.mount_FreeCAqk7dC1/usr/bin/../lib/libFreeCADApp.so+0xc2
#16  0x7f4540cf368c in Part::Feature::recompute() from /tmp/.mount_FreeCAqk7dC1/usr/lib/Part.so+0xc
#17  0x7f4547a5a73c in App::Document::_recomputeFeature(App::DocumentObject*) from /tmp/.mount_FreeCAqk7dC1/usr/bin/../lib/libFreeCADApp.so+0x24c
#18  0x7f4547ab805b in App::Document::recompute(std::vector<App::DocumentObject*, std::allocator<App::DocumentObject*> > const&, bool, bool*, int) from /tmp/.mount_FreeCAqk7dC1/usr/bin/../lib/libFreeCADApp.so+0x66b
#19  0x7f4547b5c7a0 in App::DocumentPy::recompute(_object*) from /tmp/.mount_FreeCAqk7dC1/usr/bin/../lib/libFreeCADApp.so+0x2f0
#20  0x7f4547b5c8f6 in App::DocumentPy::staticCallback_recompute(_object*, _object*) from /tmp/.mount_FreeCAqk7dC1/usr/bin/../lib/libFreeCADApp.so+0x56
#21  /tmp/.mount_FreeCAqk7dC1/usr/bin/../lib/libpython3.11.so.1.0(+0x2020d8) [0x7f45482020d8]
#22  /tmp/.mount_FreeCAqk7dC1/usr/bin/../lib/libpython3.11.so.1.0(_PyObject_MakeTpCall+0x25c) [0x7f45481e2cec]
#23  /tmp/.mount_FreeCAqk7dC1/usr/bin/../lib/libpython3.11.so.1.0(_PyEval_EvalFrameDefault+0x6f2) [0x7f45481ed3d2]
#24  /tmp/.mount_FreeCAqk7dC1/usr/bin/../lib/libpython3.11.so.1.0(+0x2a6e3d) [0x7f45482a6e3d]
#25  /tmp/.mount_FreeCAqk7dC1/usr/bin/../lib/libpython3.11.so.1.0(PyEval_EvalCode+0xa4) [0x7f45482a68b4]
#26  /tmp/.mount_FreeCAqk7dC1/usr/bin/../lib/libpython3.11.so.1.0(+0x2c5ae3) [0x7f45482c5ae3]
#27  /tmp/.mount_FreeCAqk7dC1/usr/bin/../lib/libpython3.11.so.1.0(+0x2c1c0a) [0x7f45482c1c0a]
#28  /tmp/.mount_FreeCAqk7dC1/usr/bin/../lib/libpython3.11.so.1.0(PyRun_StringFlags+0x69) [0x7f45482b5b09]
#29  0x7f454633c00c in Base::InterpreterSingleton::runString[abi:cxx11](char const*) from /tmp/.mount_FreeCAqk7dC1/usr/bin/../lib/libFreeCADBase.so+0x6c
#30  0x7f4548c921a4 in Gui::Command::_runCommand(char const*, int, Gui::Command::DoCmd_Type, char const*) from /tmp/.mount_FreeCAqk7dC1/usr/bin/../lib/libFreeCADGui.so+0x94
#31  0x7f4548c92333 in Gui::Command::_doCommand(char const*, int, Gui::Command::DoCmd_Type, char const*, ...) from /tmp/.mount_FreeCAqk7dC1/usr/bin/../lib/libFreeCADGui.so+0xe3
#32  0x7f43d2e20a31 in SpreadsheetGui::SheetModel::setData(QModelIndex const&, QVariant const&, int) from /tmp/.mount_FreeCAqk7dC1/usr/lib/SpreadsheetGui.so+0x3c1
#33  0x7f43d2e06988 in SpreadsheetGui::SpreadsheetDelegate::setModelData(QWidget*, QAbstractItemModel*, QModelIndex const&) const from /tmp/.mount_FreeCAqk7dC1/usr/lib/SpreadsheetGui.so+0xb8
#34  0x7f45474ee348 in QAbstractItemView::commitData(QWidget*) from /tmp/.mount_FreeCAqk7dC1/usr/bin/../lib/libQt5Widgets.so.5+0x8e
#35  /tmp/.mount_FreeCAqk7dC1/usr/bin/../lib/libQt5Core.so.5(+0x1dfff5) [0x7f45467dfff5]
#36  0x7f45474fe3e9 in QAbstractItemDelegate::commitData(QWidget*) from /tmp/.mount_FreeCAqk7dC1/usr/bin/../lib/libQt5Widgets.so.5+0x2f
#37  0x7f43d2e04cbc in SpreadsheetGui::SpreadsheetDelegate::commitAndCloseEditor() from /tmp/.mount_FreeCAqk7dC1/usr/lib/SpreadsheetGui.so+0xac
#38  0x7f43d2e04dd2 in SpreadsheetGui::SpreadsheetDelegate::onEditorFinishedWithKey(int, QFlags<Qt::KeyboardModifier>) from /tmp/.mount_FreeCAqk7dC1/usr/lib/SpreadsheetGui.so+0x12
#39  /tmp/.mount_FreeCAqk7dC1/usr/bin/../lib/libQt5Core.so.5(+0x1dff9b) [0x7f45467dff9b]
#40  0x7f43d2de9fd6 in SpreadsheetGui::TextEdit::finishedWithKey(int, QFlags<Qt::KeyboardModifier>) from /tmp/.mount_FreeCAqk7dC1/usr/lib/SpreadsheetGui.so+0x56
#41  0x7f43d2dea543 in SpreadsheetGui::TextEdit::event(QEvent*) from /tmp/.mount_FreeCAqk7dC1/usr/lib/SpreadsheetGui.so+0x133
#42  0x7f454736a087 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_FreeCAqk7dC1/usr/bin/../lib/libQt5Widgets.so.5+0xd9
#43  0x7f454736e0cc in QApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAqk7dC1/usr/bin/../lib/libQt5Widgets.so.5+0x3c2
#44  0x7f4548c11f09 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAqk7dC1/usr/bin/../lib/libFreeCADGui.so+0x99
#45  0x7f45467c2a18 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_FreeCAqk7dC1/usr/bin/../lib/libQt5Core.so.5+0x8e
#46  /tmp/.mount_FreeCAqk7dC1/usr/bin/../lib/libQt5Widgets.so.5(+0x1a44f5) [0x7f45473a44f5]
#47  0x7f454736a087 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_FreeCAqk7dC1/usr/bin/../lib/libQt5Widgets.so.5+0xd9
#48  0x7f4548c11f09 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAqk7dC1/usr/bin/../lib/libFreeCADGui.so+0x99
#49  0x7f45467c2a18 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_FreeCAqk7dC1/usr/bin/../lib/libQt5Core.so.5+0x8e
#50  0x7f4546d073e3 in QGuiApplicationPrivate::processKeyEvent(QWindowSystemInterfacePrivate::KeyEvent*) from /tmp/.mount_FreeCAqk7dC1/usr/bin/../lib/libQt5Gui.so.5+0xcd
#51  0x7f4546cf6091 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAqk7dC1/usr/bin/../lib/libQt5Gui.so.5+0x57
#52  /tmp/.mount_FreeCAqk7dC1/usr/plugins/platforms/../../lib/libQt5XcbQpa.so.5(+0x5672c) [0x7f453ba9f72c]
#53  /tmp/.mount_FreeCAqk7dC1/usr/bin/../lib/./libglib-2.0.so.0(+0x5a417) [0x7f4544b11417]
#54  /tmp/.mount_FreeCAqk7dC1/usr/bin/../lib/./libglib-2.0.so.0(+0x5d3c7) [0x7f4544b143c7]
#55  /tmp/.mount_FreeCAqk7dC1/usr/bin/../lib/./libglib-2.0.so.0(g_main_context_iteration+0x2e) [0x7f4544b149be]
#56  0x7f45467f3d50 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAqk7dC1/usr/bin/../lib/libQt5Core.so.5+0x5c
#57  0x7f45467c05d8 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAqk7dC1/usr/bin/../lib/libQt5Core.so.5+0x180
#58  0x7f45467c47af in QCoreApplication::exec() from /tmp/.mount_FreeCAqk7dC1/usr/bin/../lib/libQt5Core.so.5+0x107
#59  0x7f4548b72c26 in Gui::Application::runApplication() from /tmp/.mount_FreeCAqk7dC1/usr/bin/../lib/libFreeCADGui.so+0x4b6
#60  ./FreeCADLink(+0x87e6) [0x55af065847e6]
#61  /usr/lib/libc.so.6(+0x27cd0) [0x7f4545e62cd0]
#62  /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7f4545e62d8a]
#63  ./FreeCADLink(+0x8bad) [0x55af06584bad]

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by realthunder** [comment]
It would be better if you can post your file here.
